"""Append 254 frog facts to frogfacts/facts.json (frog_0305 to frog_0558)."""
import json
from pathlib import Path

FILE = Path(__file__).parent / "frogfacts" / "facts.json"
data = json.loads(FILE.read_text(encoding="utf-8"))

new_items = [
{"id":"frog_0305","fact":"Frogs can survive being frozen solid during winter and thaw back to life in spring thanks to glucose acting as a natural antifreeze in their cells."},
{"id":"frog_0306","fact":"The poison dart frog gets its toxins entirely from the insects it eats in the wild — captive frogs fed different diets become completely non-toxic."},
{"id":"frog_0307","fact":"A group of frogs is called an army."},
{"id":"frog_0308","fact":"Frogs were the first land animals to develop true vocal cords."},
{"id":"frog_0309","fact":"The blue poison dart frog carries enough toxin to kill up to 10 adult humans."},
{"id":"frog_0310","fact":"Frogs absorb water through their skin rather than drinking it with their mouths."},
{"id":"frog_0311","fact":"The goliath frog of Central Africa is the world's largest frog, growing up to 32 cm long and weighing over 3 kg."},
{"id":"frog_0312","fact":"The Paedophryne amauensis frog from Papua New Guinea is the world's smallest vertebrate, measuring just 7.7 mm long."},
{"id":"frog_0313","fact":"Some frogs can leap over 20 times their own body length in a single jump."},
{"id":"frog_0314","fact":"Frogs have existed on Earth for over 265 million years, surviving three mass extinction events."},
{"id":"frog_0315","fact":"The American wood frog can survive temperatures as low as -16°C by freezing solid, with its heart completely stopped."},
{"id":"frog_0316","fact":"Frogs cannot survive in salt water because the salt dehydrates them through osmosis."},
{"id":"frog_0317","fact":"Male frogs generally call to attract females; the loudest frog relative to body size is the Puerto Rican coqui, audible 100 metres away."},
{"id":"frog_0318","fact":"The glass frog has transparent skin on its underside, allowing you to see its beating heart and other organs."},
{"id":"frog_0319","fact":"Frogs have no ribs and rely on their mouth to force air into their lungs."},
{"id":"frog_0320","fact":"The strawberry poison dart frog carries its tadpoles on its back to deposit them individually in separate pools of water."},
{"id":"frog_0321","fact":"Some tree frogs produce a waxy secretion that they spread over their bodies to prevent dehydration in dry climates."},
{"id":"frog_0322","fact":"The African clawed frog was widely used as a pregnancy test in the 1930s–60s — injecting a woman's urine caused it to lay eggs if she was pregnant."},
{"id":"frog_0323","fact":"Frogs shed their skin roughly once a week and usually eat it immediately after shedding."},
{"id":"frog_0324","fact":"The Wallace's flying frog can glide up to 15 metres through the air using its webbed feet as wings."},
{"id":"frog_0325","fact":"A frog's tongue is attached at the front of its mouth, not the back, allowing it to flip out rapidly and retract with prey."},
{"id":"frog_0326","fact":"The tongue of a frog can be twice as sticky as conventional pressure-sensitive adhesives."},
{"id":"frog_0327","fact":"Frogs have a 270-degree field of vision and can see in almost all directions at once."},
{"id":"frog_0328","fact":"The hairy frog, also called the horror frog, breaks its own toe bones to create claws when threatened."},
{"id":"frog_0329","fact":"Frogs have three-chambered hearts, unlike the four-chambered hearts of mammals and birds."},
{"id":"frog_0330","fact":"The tomato frog puffs itself up dramatically and secretes a sticky white substance to deter predators."},
{"id":"frog_0331","fact":"Male Darwin's frogs swallow fertilised eggs and carry them in their vocal sac until the tadpoles fully develop."},
{"id":"frog_0332","fact":"Frogs can detect sound through their lungs as well as through their eardrums."},
{"id":"frog_0333","fact":"The gastric-brooding frog of Australia would swallow its eggs and raise tadpoles in its stomach — it became extinct in 1983."},
{"id":"frog_0334","fact":"Frogs play a critical role in ecosystems as both predators of insects and prey for birds, snakes, and mammals."},
{"id":"frog_0335","fact":"The red-eyed tree frog's vivid red eyes are thought to startle predators, giving it a split second to escape."},
{"id":"frog_0336","fact":"Some frogs can change colour slightly based on temperature, light, or mood, similar to chameleons."},
{"id":"frog_0337","fact":"The mimic poison frog copies the colour patterns of more toxic species to deter predators without being toxic itself."},
{"id":"frog_0338","fact":"Frogs have been found living on every continent except Antarctica."},
{"id":"frog_0339","fact":"The Titicaca water frog never surfaces to breathe — it absorbs all its oxygen through highly wrinkled skin."},
{"id":"frog_0340","fact":"Tadpoles of some frog species can detect predators by smell and change their development speed in response."},
{"id":"frog_0341","fact":"The Amazon milk frog gets its name from the milky toxic substance it secretes when stressed."},
{"id":"frog_0342","fact":"Some frogs use their front legs to push food into their mouths by pressing their eyeballs downward into the roof of the mouth."},
{"id":"frog_0343","fact":"The shovel-nosed frog uses its hardened snout to burrow headfirst into the ground."},
{"id":"frog_0344","fact":"Frogs have colour vision and can see well in very low light conditions."},
{"id":"frog_0345","fact":"The Surinam toad carries its eggs embedded in pockets of skin on its back until the young emerge as fully formed toadlets."},
{"id":"frog_0346","fact":"Baby frogs are called froglets after they have absorbed their tails but before they are fully grown."},
{"id":"frog_0347","fact":"The calls of frogs were the first animal sounds ever recorded, captured in 1900 in the United States."},
{"id":"frog_0348","fact":"Some species of frog can detect the vibrations of approaching predators through the ground before hearing them."},
{"id":"frog_0349","fact":"The ornate horned frog, or Pac-Man frog, will attempt to eat anything that moves within reach including mice and other frogs."},
{"id":"frog_0350","fact":"Frogs must keep their skin moist to breathe — a dry frog will quickly suffocate."},
{"id":"frog_0351","fact":"The African bullfrog is one of the most aggressive frogs, guarding tadpole pools and biting predators including humans."},
{"id":"frog_0352","fact":"Some frogs hibernate in mud at the bottom of ponds during winter, breathing only through their skin."},
{"id":"frog_0353","fact":"The coqui frog of Puerto Rico was accidentally introduced to Hawaii and has disrupted local ecosystems by eating huge quantities of insects."},
{"id":"frog_0354","fact":"Frogs have been used in neuroscience research for centuries — Luigi Galvani discovered bioelectricity through frog leg experiments in 1780."},
{"id":"frog_0355","fact":"The spadefoot toad can lie dormant underground for up to 11 months, waiting for rain to trigger activity."},
{"id":"frog_0356","fact":"A frog egg typically hatches into a tadpole within 6 to 21 days depending on species and temperature."},
{"id":"frog_0357","fact":"The golden poison frog of Colombia is considered the most toxic vertebrate on Earth — one frog carries enough poison for 20,000 mice."},
{"id":"frog_0358","fact":"Frogs use a technique called cutaneous respiration, where up to 50% of their gas exchange happens directly through the skin."},
{"id":"frog_0359","fact":"The waxy monkey tree frog spreads lipid secretions over its entire body to waterproof itself in dry environments."},
{"id":"frog_0360","fact":"In many frog species, temperature during egg development determines the sex of offspring rather than genetics."},
{"id":"frog_0361","fact":"The mossy frog of Vietnam looks exactly like a clump of moss, making it almost invisible in its forest habitat."},
{"id":"frog_0362","fact":"Frogs have no external ears — the circular disc visible behind their eyes is the tympanum, a direct eardrum."},
{"id":"frog_0363","fact":"Some frogs lay their eggs on leaves above water so the tadpoles drop into the water below when they hatch."},
{"id":"frog_0364","fact":"The purple frog of India spends almost its entire life underground, only surfacing for two weeks a year to breed."},
{"id":"frog_0365","fact":"Frogs were among the first organisms sent to space — a French Pelobates frog was launched on a sounding rocket in 1970."},
{"id":"frog_0366","fact":"The túngara frog of Central America produces foam nests on the water surface to protect its eggs from drying out."},
{"id":"frog_0367","fact":"Some frogs produce calls so loud they can exceed 90 decibels — equivalent to a lawnmower."},
{"id":"frog_0368","fact":"The burrowing frog of Australia can absorb water through its skin from damp soil without needing a pool or puddle."},
{"id":"frog_0369","fact":"Frogs can regenerate lost limbs during their tadpole stage, but lose this ability as adults."},
{"id":"frog_0370","fact":"The paradox frog of South America shrinks as it matures — its tadpoles can be four times larger than the adult frog."},
{"id":"frog_0371","fact":"Some species of tree frog can glue their eggs to vertical surfaces using specially adhesive jelly."},
{"id":"frog_0372","fact":"The wood frog produces urea as part of its freeze-tolerance mechanism, concentrating it in cells as a cryoprotectant."},
{"id":"frog_0373","fact":"Frogs' eyes can be retracted into the skull to help push food down the throat during swallowing."},
{"id":"frog_0374","fact":"Chytrid fungus (Batrachochytrium dendrobatidis) has caused more extinctions than any other pathogen in recorded history, devastating frog populations worldwide."},
{"id":"frog_0375","fact":"The desert rain frog of Namibia produces a high-pitched squeaking call that sounds nothing like a typical frog."},
{"id":"frog_0376","fact":"Female frogs of many species are larger than males — the opposite of most mammals."},
{"id":"frog_0377","fact":"The banded rubber frog of Africa inflates itself and tilts its body to display a bright red warning pattern when threatened."},
{"id":"frog_0378","fact":"Frogs have been found fossilised inside amber, perfectly preserved from millions of years ago."},
{"id":"frog_0379","fact":"The tailed frog of North America is the only frog species with internal fertilisation — the male's tail is actually a copulatory organ."},
{"id":"frog_0380","fact":"Many frog species are nocturnal, using their large eyes to navigate and hunt in near-total darkness."},
{"id":"frog_0381","fact":"The smoky jungle frog of South America can exceed 18 cm in length and is one of the largest frogs in the Americas."},
{"id":"frog_0382","fact":"Tadpoles of some species are cannibalistic, consuming unfertilised eggs or smaller siblings to survive."},
{"id":"frog_0383","fact":"The African foam nest tree frog creates a communal foam nest where multiple females lay eggs together."},
{"id":"frog_0384","fact":"Frogs have a nictitating membrane, a transparent third eyelid that protects the eye underwater."},
{"id":"frog_0385","fact":"The Indian purple frog was only discovered and described by science in 2003 despite being an ancient lineage."},
{"id":"frog_0386","fact":"Some frog species communicate by waving their feet, a behaviour called foot flagging, especially in noisy stream environments."},
{"id":"frog_0387","fact":"The pebble toad of Venezuela rolls itself into a ball and bounces down rocky slopes to escape predators."},
{"id":"frog_0388","fact":"Frogs have been present in folk medicine and mythology across virtually every culture on Earth."},
{"id":"frog_0389","fact":"The glass frog's transparent abdomen reveals its liver, intestines, and sometimes visible heartbeat to the naked eye."},
{"id":"frog_0390","fact":"Most frogs return to the same pond or water body every year to breed, often travelling kilometres to do so."},
{"id":"frog_0391","fact":"The splash-back poison frog deposits individual tadpoles in water-filled bromeliads and then feeds them unfertilised eggs."},
{"id":"frog_0392","fact":"Frogs were once used to test the freshness of butter — a frog placed in a milk churn was said to prevent souring."},
{"id":"frog_0393","fact":"The Solomon Islands leaf frog gives birth to fully formed froglets directly, skipping the aquatic tadpole stage entirely."},
{"id":"frog_0394","fact":"Some horned frogs have a bite force proportional to body size equivalent to a large dog."},
{"id":"frog_0395","fact":"Albino frogs occur in the wild but rarely survive due to their visibility to predators."},
{"id":"frog_0396","fact":"Frogs have been clocked jumping at over 17 body-lengths per second — one of the fastest accelerations in the animal kingdom."},
{"id":"frog_0397","fact":"The fire-bellied toad arches its back to display its brightly coloured underside as a warning to predators."},
{"id":"frog_0398","fact":"Some tree frogs have toe pads that create wet adhesion, functioning like thousands of tiny suction cups."},
{"id":"frog_0399","fact":"The river frog of sub-Saharan Africa is the largest frog on the African continent, reaching 12 cm."},
{"id":"frog_0400","fact":"Frog embryos can detect vibrations from predatory wasps and hatch early to escape before the eggs are eaten."},
{"id":"frog_0401","fact":"There are over 7,000 known species of frog, making them the most diverse group of amphibians."},
{"id":"frog_0402","fact":"The American bullfrog can eat anything it can fit in its mouth, including birds, bats, and small alligators."},
{"id":"frog_0403","fact":"Many frogs have toxic skin secretions as a defence but only a small fraction of species produce truly dangerous toxins."},
{"id":"frog_0404","fact":"Frogs have been used in scientific research to produce the first test-tube babies — via hormone injections pioneered using frogs."},
{"id":"frog_0405","fact":"The Amazonian milk frog secretes a white poisonous substance and has unusually large toe pads for climbing."},
{"id":"frog_0406","fact":"Frogs lay between 2 and 30,000 eggs depending on species — species with fewer eggs tend to provide more parental care."},
{"id":"frog_0407","fact":"The flying frog genus Rhacophorus can control its glide by adjusting the angle of its webbed feet."},
{"id":"frog_0408","fact":"Frog skin contains antimicrobial peptides that researchers are studying for use in human medicine."},
{"id":"frog_0409","fact":"The water-holding frog of Australia wraps itself in a mucus cocoon to prevent water loss during droughts lasting years."},
{"id":"frog_0410","fact":"Male midwife toads of Europe wrap strings of eggs around their hind legs and carry them until they hatch."},
{"id":"frog_0411","fact":"Frogs were the first animals used in a biological pregnancy test — the Hogben test, used from the 1930s to 1960s."},
{"id":"frog_0412","fact":"The phantasmal poison frog's toxin, epibatidine, is 200 times more effective as a painkiller than morphine."},
{"id":"frog_0413","fact":"Some frog species that coexist with toxic counterparts evolve similar coloration through Mullerian mimicry."},
{"id":"frog_0414","fact":"Frogs have been found at altitudes above 5,400 metres in the Andes mountains."},
{"id":"frog_0415","fact":"The Cape rain frog of South Africa is extremely round and cannot jump — it can only walk."},
{"id":"frog_0416","fact":"Frogs' kidneys filter waste very efficiently, allowing them to retain water in dry conditions."},
{"id":"frog_0417","fact":"The green and black poison dart frog performs elaborate courtship dances before mating."},
{"id":"frog_0418","fact":"Frog fossils from the Triassic period show they had the same jumping anatomy as modern frogs."},
{"id":"frog_0419","fact":"Some frog tadpoles scrape algae off rocks with rows of small teeth they lose after metamorphosis."},
{"id":"frog_0420","fact":"The Japanese tree frog changes colour from green to brown depending on the surface it is sitting on."},
{"id":"frog_0421","fact":"Frogs were associated with fertility and rebirth in ancient Egyptian mythology."},
{"id":"frog_0422","fact":"The Borneo flat-headed frog has no lungs at all and breathes entirely through its highly flattened, wrinkled skin."},
{"id":"frog_0423","fact":"Some frog species in cold climates can delay metamorphosis by years, remaining as tadpoles until conditions improve."},
{"id":"frog_0424","fact":"The calls of Australian frog species are so distinct that scientists use recorded calls to conduct population surveys."},
{"id":"frog_0425","fact":"Frogs have a complete digestive system but lack a diaphragm — they use body wall muscles to breathe."},
{"id":"frog_0426","fact":"The Arum frog of South Africa shelters inside the flowers of the arum lily to ambush insects."},
{"id":"frog_0427","fact":"Many frogs orient themselves using the Earth's magnetic field to navigate back to their breeding ponds."},
{"id":"frog_0428","fact":"The Budgett's frog has a huge mouth and screams loudly when threatened — it will also bite."},
{"id":"frog_0429","fact":"Some poison dart frogs have individual colour patterns unique enough to identify individuals, like fingerprints."},
{"id":"frog_0430","fact":"Frog populations worldwide have declined by about 50% since 1970, making them the most threatened vertebrate group."},
{"id":"frog_0431","fact":"The Mozambique rain frog has such an inflated, round body shape that it looks like a small balloon with legs."},
{"id":"frog_0432","fact":"Frogs were among the earliest animals to colonise land, evolving from aquatic ancestors around 370 million years ago."},
{"id":"frog_0433","fact":"The dyeing poison dart frog was traditionally used by indigenous Amazonians to dye parrot feathers for headdresses."},
{"id":"frog_0434","fact":"Baby frogs can miniaturise their jumping technique to leap relatively farther than adult frogs of the same species."},
{"id":"frog_0435","fact":"The Phrynomantis microps, a small West African frog, releases a toxic mucus that causes severe pain if it contacts human skin."},
{"id":"frog_0436","fact":"Some frogs can jump in any direction immediately upon landing, with no wind-up required."},
{"id":"frog_0437","fact":"The barking tree frog of the southeastern United States makes a call that sounds remarkably like a dog barking."},
{"id":"frog_0438","fact":"Frogs' ancestors likely had tails as adults — modern frogs evolved the tailless adult form for more efficient jumping."},
{"id":"frog_0439","fact":"The giant monkey frog of Peru secretes a waxy substance scientists are investigating for potential cancer treatments."},
{"id":"frog_0440","fact":"Some frogs can vocalize both above and below water by vibrating their vocal cords in different ways."},
{"id":"frog_0441","fact":"The skin of many frog species contains bacteria that produce antibiotics, which scientists are studying for medical use."},
{"id":"frog_0442","fact":"Frogs were featured in the first recorded use of animals in entertainment — ancient Egyptian hieroglyphs depict frog acrobats."},
{"id":"frog_0443","fact":"The paradox frog has one of the most extreme size reversals of any vertebrate — adults are up to four times smaller than their tadpoles."},
{"id":"frog_0444","fact":"In many cultures, frogs appearing in large numbers after rain are seen as a sign of good fortune."},
{"id":"frog_0445","fact":"The Phantasmal poison frog's skin secretions are being studied as a potential alternative to morphine for pain relief."},
{"id":"frog_0446","fact":"Frogs have been found in the stomachs of prey fish in Australia — some small frogs appear able to survive ingestion."},
{"id":"frog_0447","fact":"The smooth guardian frog of Borneo is known for its intensive parental care, with fathers guarding egg clutches for weeks."},
{"id":"frog_0448","fact":"Some frog species form breeding aggregations of thousands of individuals, making the collective calls audible from over a kilometre away."},
{"id":"frog_0449","fact":"The Breviceps, or rain frog genus, has such short legs that the male must use adhesive secretions to hold on to the female during mating."},
{"id":"frog_0450","fact":"Frogs were the first vertebrates to have both aquatic and terrestrial life stages studied in comparative biology."},
{"id":"frog_0451","fact":"The adult gastric-brooding frog would stop producing stomach acid entirely while brooding young in its stomach."},
{"id":"frog_0452","fact":"Some male frogs can produce both male and female sex cells simultaneously due to atrazine herbicide exposure."},
{"id":"frog_0453","fact":"The giant tree frog of Australia is the largest tree frog in the world, reaching up to 15 cm."},
{"id":"frog_0454","fact":"Frogs' blood contains clotting agents so efficient that research into them has influenced treatment of human bleeding disorders."},
{"id":"frog_0455","fact":"The painted frog of Europe is considered a living fossil as its anatomy has changed little in 10 million years."},
{"id":"frog_0456","fact":"The Amolops frogs of Asia have sucker-like pads on their fingers and toes to cling to rocks in fast-moving streams."},
{"id":"frog_0457","fact":"Frogs can live from 2 years to over 40 years depending on species — the African bullfrog can live 45 years."},
{"id":"frog_0458","fact":"Some frogs produce specific calls only during disputes with rivals, distinct from their mating and alarm calls."},
{"id":"frog_0459","fact":"The harlequin frog is so named for its brilliant patterning — over 100 species in this group are now extinct or critically endangered."},
{"id":"frog_0460","fact":"Frogs have a specialized organ called the Bidder's organ in males, which can develop into functional ovaries if testosterone is removed."},
{"id":"frog_0461","fact":"The red tree frog of Australia presses its body flat against leaves during the day to minimise water loss."},
{"id":"frog_0462","fact":"Some frog embryos can smell chemical cues from predatory snakes and accelerate their hatching to escape."},
{"id":"frog_0463","fact":"The Nasikabatrachus sahyadrensis, the Indian purple frog, separated from its closest relatives 130 million years ago."},
{"id":"frog_0464","fact":"Frogs inspired the design of robotic jumping legs because their tendons store and release energy like a spring."},
{"id":"frog_0465","fact":"The mottled shovel-nosed frog uses its disc-shaped head to seal burrow entrances and protect eggs from predators."},
{"id":"frog_0466","fact":"Some poison dart frogs raised in captivity and reintroduced to the wild become toxic again once they eat wild insects."},
{"id":"frog_0467","fact":"The chorus frog can be heard chorusing in spring in North America before the last winter snow has fully melted."},
{"id":"frog_0468","fact":"Some frogs have sticky pads that can support over 14 times their own body weight against a smooth vertical surface."},
{"id":"frog_0469","fact":"Frogs shed and eat their skin to recycle the proteins and avoid leaving a scent trail for predators."},
{"id":"frog_0470","fact":"The Dendrobates azureus, or blue poison dart frog, has a home range of only a few square metres in the wild."},
{"id":"frog_0471","fact":"Frogs can survive in salinity levels up to 60% of sea water for short periods, despite generally being freshwater animals."},
{"id":"frog_0472","fact":"The Malagasy rainbow frog is so prized in the pet trade it is now critically endangered in its native Madagascar."},
{"id":"frog_0473","fact":"Many tree frogs can sleep during the day in full sunlight by adopting a tight ball posture to reduce exposed skin area."},
{"id":"frog_0474","fact":"The tungara frog's foam nest contains antimicrobial compounds that protect developing eggs from bacterial infection."},
{"id":"frog_0475","fact":"Frogs are indicators of environmental health — a decline in frog populations often signals pollution or habitat degradation."},
{"id":"frog_0476","fact":"The male tree frog Hyla ebraccata adds complexity to its call to attract females away from competing males."},
{"id":"frog_0477","fact":"Frogs are studied extensively to understand limb regeneration because their close relatives, salamanders, can regrow lost limbs."},
{"id":"frog_0478","fact":"The South American marsupial frog carries its eggs in a pouch on its back, similar to a kangaroo."},
{"id":"frog_0479","fact":"Some frog species produce a smell similar to peanut butter — scientists have identified the chemical compounds responsible."},
{"id":"frog_0480","fact":"The largest prehistoric frog, Beelzebufo, lived 70 million years ago in Madagascar and was the size of a football."},
{"id":"frog_0481","fact":"Frogs have been found living in the burrows of mammals including armadillos, using them for shelter."},
{"id":"frog_0482","fact":"The squeaker frogs of Africa are so named for their tiny, high-pitched calls that sound like a rubber toy."},
{"id":"frog_0483","fact":"Frog eyes are protected by a transparent nictitating membrane while the frog eats, as the eyes retract to assist swallowing."},
{"id":"frog_0484","fact":"Some Australian frogs store water in their bladder as an emergency reserve, a strategy used by indigenous Australians to find water in the desert."},
{"id":"frog_0485","fact":"The European common frog can travel up to 500 metres in a single night to reach its breeding pond."},
{"id":"frog_0486","fact":"Frogs' colour patterns can serve as camouflage, warning, mimicry, or species identification depending on the species."},
{"id":"frog_0487","fact":"The Limon giant glass frog has a striking green coloration with visible internal organs through its chest."},
{"id":"frog_0488","fact":"Frogs communicate danger through chemical signals released into the water as well as through vocalisations."},
{"id":"frog_0489","fact":"The phantasmal poison frog is currently being studied for its potential to replace morphine in modern medicine."},
{"id":"frog_0490","fact":"Some male frogs release a distress call when grabbed — scientists believe this may confuse predators expecting a non-vocal prey animal."},
{"id":"frog_0491","fact":"The largest frog chorus ever recorded contained an estimated 10 million individual frogs calling simultaneously in Brazil."},
{"id":"frog_0492","fact":"Frogs can live completely underwater as adults in some species, breathing only through their skin."},
{"id":"frog_0493","fact":"The spotted tree frog of southeastern Australia is critically endangered due to the chytrid fungus epidemic."},
{"id":"frog_0494","fact":"Some tropical frog species never touch the ground, spending their entire lives in the rainforest canopy."},
{"id":"frog_0495","fact":"Frogs' livers are proportionally very large and perform crucial detoxification roles for the skin toxins the frogs carry."},
{"id":"frog_0496","fact":"The transparent glass frog egg masses are laid on leaves, and the embryos inside can be seen developing with the naked eye."},
{"id":"frog_0497","fact":"Some frogs mimic the calls of other more toxic species to benefit from their reputation without being toxic themselves."},
{"id":"frog_0498","fact":"The rain frog genus Breviceps cannot swim and will drown if placed in water — they live entirely on land."},
{"id":"frog_0499","fact":"Frogs have inspired architectural designs — their ribbed skin has been studied for waterproofing building materials."},
{"id":"frog_0500","fact":"The golden toad of Costa Rica was last seen in 1989 and is considered one of the first species to go extinct due to climate change."},
{"id":"frog_0501","fact":"Frogs can detect the magnetic north using magnetite particles in their bodies, similar to migratory birds."},
{"id":"frog_0502","fact":"The Daubenton's frog of Europe uses echolocation-like vibration detection to catch flying insects near water surfaces."},
{"id":"frog_0503","fact":"Some frog species can slow their heart rate to just a few beats per minute during hibernation."},
{"id":"frog_0504","fact":"The Indian bullfrog turns from olive green to bright yellow during the breeding season when males compete for females."},
{"id":"frog_0505","fact":"Frogs are the dominant predator of mosquitoes in many tropical wetland ecosystems."},
{"id":"frog_0506","fact":"The Natterjack toad runs instead of hopping and can sustain speeds of over 6 km/h across open ground."},
{"id":"frog_0507","fact":"Some frogs produce ultrasonic calls above human hearing range to communicate in noisy stream environments."},
{"id":"frog_0508","fact":"The egg of a dart frog is so nutritious that a single unfertilised trophic egg can sustain a tadpole for a week."},
{"id":"frog_0509","fact":"Frogs lack claws and scales — two features that helped reptiles fully conquer dry land — which is why frogs need moisture."},
{"id":"frog_0510","fact":"The cane toad, introduced to Australia in 1935, has spread to millions of hectares and devastated native wildlife."},
{"id":"frog_0511","fact":"Some South American frogs have evolved bacterial resistance in their gut to safely eat ants that kill other frogs."},
{"id":"frog_0512","fact":"Frogs' pupils can be round, horizontal, vertical, heart-shaped, or diamond-shaped depending on species."},
{"id":"frog_0513","fact":"The Microhylid frogs of Madagascar have diversified into over 200 species on a single island."},
{"id":"frog_0514","fact":"Frogs were one of the first animals to be given an official conservation status by the IUCN, in 1996."},
{"id":"frog_0515","fact":"The Cuban tree frog is the largest tree frog in North America and was accidentally introduced to Florida."},
{"id":"frog_0516","fact":"Frog spawn is vulnerable to UV radiation, and thinning ozone layers are thought to contribute to spawn mortality."},
{"id":"frog_0517","fact":"The Knudsen's tree frog produces such a loud call for its size that it has been measured at 93.8 decibels."},
{"id":"frog_0518","fact":"Some frogs can smell the difference between species and prefer to mate only with frogs of the same species."},
{"id":"frog_0519","fact":"The treefrog Agalychnis spurrelli falls from trees in large groups when startled, landing softly due to their light bodies."},
{"id":"frog_0520","fact":"Frogs' bones are so lightweight that even large species weigh far less than a mammal of similar body length."},
{"id":"frog_0521","fact":"The black rain frog of South Africa makes a distinctly unhappy-looking frown face, making it popular on the internet."},
{"id":"frog_0522","fact":"Some frogs can tolerate being out of water for months by entering a state called aestivation, similar to hibernation."},
{"id":"frog_0523","fact":"The world's most poisonous frog, the golden poison dart frog, is harmless to handle in captivity because it has no dietary source of toxins."},
{"id":"frog_0524","fact":"Frogs' ears are tuned to hear the specific frequency of their own species' call to filter out background noise."},
{"id":"frog_0525","fact":"Some rainforest frogs use leaf litter as drums, slapping the ground with their limbs to send seismic signals to rivals."},
{"id":"frog_0526","fact":"The American bullfrog can leap 2 metres in a single jump — nearly 10 times its body length."},
{"id":"frog_0527","fact":"Frogs existed before the dinosaurs — they were present in the Triassic period over 240 million years ago."},
{"id":"frog_0528","fact":"The corroboree frog of Australia actually synthesises its own toxins rather than obtaining them from diet."},
{"id":"frog_0529","fact":"Frogs can survive in salt marshes for short periods by rapidly excreting excess salt through their skin."},
{"id":"frog_0530","fact":"The Vietnamese mossy frog is covered in green and black tubercles making it indistinguishable from moss-covered bark."},
{"id":"frog_0531","fact":"Some frog species lay eggs in terrestrial nests rather than water, and the embryos develop directly into froglets."},
{"id":"frog_0532","fact":"Frogs' lifespan in the wild is often much shorter than in captivity due to predation and environmental hazards."},
{"id":"frog_0533","fact":"The wax frog of Brazil can survive air temperatures of 48°C by covering itself in its own waxy secretion to prevent water loss."},
{"id":"frog_0534","fact":"Frogs have a transparent structure in their cornea that acts as a polarising filter, reducing glare off water surfaces."},
{"id":"frog_0535","fact":"The hairy frog's protruding ribs can break through the skin at will to act as defensive spines."},
{"id":"frog_0536","fact":"Some toads can live over 30 years — the common European toad can reach 40 years in captivity."},
{"id":"frog_0537","fact":"Frogs have been found fossilised mid-jump, providing direct evidence of their ancient jumping abilities."},
{"id":"frog_0538","fact":"The Amazon horned frog is nicknamed the Pac-Man frog because it is nearly as wide as it is long."},
{"id":"frog_0539","fact":"Some frog tadpoles secrete chemicals that prevent nearby eggs from hatching, reducing competition for food."},
{"id":"frog_0540","fact":"The common midwife toad emits a bird-like whistle rather than a croaking sound."},
{"id":"frog_0541","fact":"Frogs were the first vertebrates to be successfully cloned — tadpole cloning experiments were conducted in the 1960s."},
{"id":"frog_0542","fact":"The Dendrobates tinctorius, the dyeing poison dart frog, comes in over 100 distinct colour morphs."},
{"id":"frog_0543","fact":"Frogs have no neck — their head and body are fused, so they cannot turn their head without turning their whole body."},
{"id":"frog_0544","fact":"The running frog of Africa has a running gait rather than a hopping one, unusual among frogs."},
{"id":"frog_0545","fact":"Some tree frogs can completely change their skin texture from smooth to spiny in under a minute."},
{"id":"frog_0546","fact":"Frogs can be trained to associate certain sounds with rewards, demonstrating a basic form of associative learning."},
{"id":"frog_0547","fact":"The bicoloured frog of India builds a foam nest over a burrow so tadpoles can develop underground in safety."},
{"id":"frog_0548","fact":"Frogs do not generate their own body heat — they are fully dependent on their environment for thermoregulation."},
{"id":"frog_0549","fact":"The toad Atelopus zeteki, the Panamanian golden frog, is the national symbol of Panama and is now extinct in the wild."},
{"id":"frog_0550","fact":"Some frogs use a technique called 'freeze tolerance' where they allow ice to form between cells but prevent ice from forming inside cells."},
{"id":"frog_0551","fact":"The ghost frog of South Africa lives only on a single mountain, Table Mountain in Cape Town."},
{"id":"frog_0552","fact":"Frogs produce a natural antimicrobial compound called magainin that is being developed as an antibiotic to treat drug-resistant infections."},
{"id":"frog_0553","fact":"The Indian skipper frog can leap out of the water to catch dragonflies in mid-flight."},
{"id":"frog_0554","fact":"Frogs are featured on the coat of arms of several countries including France's historical use of frogs as a heraldic symbol."},
{"id":"frog_0555","fact":"The four-eyed frog of South America has two large false eye-spots on its rump that it displays to predators approaching from behind."},
{"id":"frog_0556","fact":"Frogs have been subjects of the Kermit chromosome study — their genome complexity has helped map repetitive DNA in vertebrates."},
{"id":"frog_0557","fact":"The marsupial frog genus Gastrotheca includes species where eggs develop in a back pouch — some complete metamorphosis there and emerge as froglets."},
{"id":"frog_0558","fact":"Frogs' eardrums are connected directly to their lungs, which is why frogs can sometimes hear sounds below the frequency range of their eardrums."},
]

data.extend(new_items)
FILE.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
print(f"Done. Total items: {len(data)}")
