"""
_bulk_eq.py — Append 272 new emoji quiz items to emojiquiz/questions.json.
IDs: eq_0281 through eq_0552.
"""

import json
from pathlib import Path

QUESTIONS_PATH = Path(__file__).parent / "emojiquiz" / "questions.json"

NEW_ITEMS_RAW = [
    # ── MOVIES ────────────────────────────────────────────────────────────────
    {"emojis": "🧙‍♂️💍🌋",          "answer": "The Lord of the Rings",        "category": "movies",      "hook": "What movie is this?"},
    {"emojis": "🦈🏖️😱",            "answer": "Jaws",                          "category": "movies",      "hook": "Name the movie!"},
    {"emojis": "👻🏚️👨‍👩‍👦",           "answer": "Ghostbusters",                 "category": "movies",      "hook": "What movie is this?"},
    {"emojis": "🤖🔴👁️",            "answer": "The Terminator",                "category": "movies",      "hook": "Name the movie!"},
    {"emojis": "🚀🌌⭐",            "answer": "Star Wars",                     "category": "movies",      "hook": "What movie is this?"},
    {"emojis": "🦇🌃🦸",            "answer": "Batman",                        "category": "movies",      "hook": "Name the superhero!"},
    {"emojis": "💎🚢❄️",            "answer": "Titanic",                       "category": "movies",      "hook": "Name the movie!"},
    {"emojis": "🧠🌀💤",            "answer": "Inception",                     "category": "movies",      "hook": "What movie is this?"},
    {"emojis": "🦕🏝️🔬",            "answer": "Jurassic Park",                 "category": "movies",      "hook": "Name the movie!"},
    {"emojis": "🌪️👠🐕",            "answer": "The Wizard of Oz",              "category": "movies",      "hook": "What movie is this?"},
    {"emojis": "🤿🐠🐟",            "answer": "Finding Nemo",                  "category": "movies",      "hook": "Name the movie!"},
    {"emojis": "🐀🍽️👨‍🍳",           "answer": "Ratatouille",                   "category": "movies",      "hook": "What movie is this?"},
    {"emojis": "🤸‍♀️🦸‍♀️⚡",           "answer": "Wonder Woman",                  "category": "movies",      "hook": "Name the superhero!"},
    {"emojis": "🪀🤠🐍",            "answer": "Toy Story",                     "category": "movies",      "hook": "What movie is this?"},
    {"emojis": "🚗⚡🏎️",            "answer": "Cars",                          "category": "movies",      "hook": "Name the movie!"},
    {"emojis": "🎪🐘🌟",            "answer": "Dumbo",                         "category": "movies",      "hook": "What movie is this?"},
    {"emojis": "🐠🐙🌊",            "answer": "Finding Dory",                  "category": "movies",      "hook": "Name the movie!"},
    {"emojis": "🦊🐰🌆",            "answer": "Zootopia",                      "category": "movies",      "hook": "What movie is this?"},
    {"emojis": "🎈👊💪",            "answer": "Up",                            "category": "movies",      "hook": "Name the movie!"},
    {"emojis": "🏎️💨🎬",            "answer": "Fast & Furious",                "category": "movies",      "hook": "What movie is this?"},
    {"emojis": "🕵️‍♂️🔍🧩",           "answer": "Sherlock Holmes",               "category": "movies",      "hook": "Name the movie!"},
    {"emojis": "🦸‍♂️🕸️🌆",           "answer": "Spider-Man: No Way Home",       "category": "movies",      "hook": "What movie is this?"},
    {"emojis": "🌹👹🏰",            "answer": "Beauty and the Beast",          "category": "movies",      "hook": "Name the movie!"},
    {"emojis": "🧜‍♀️🐚🌊",           "answer": "The Little Mermaid",            "category": "movies",      "hook": "What movie is this?"},
    {"emojis": "👸🍎💤",            "answer": "Snow White",                    "category": "movies",      "hook": "Name the movie!"},
    {"emojis": "👠⏰💃",            "answer": "Cinderella",                    "category": "movies",      "hook": "What movie is this?"},
    {"emojis": "🐙🏴‍☠️⚓",           "answer": "Pirates of the Caribbean",      "category": "movies",      "hook": "Name the movie!"},
    {"emojis": "🦁🐻❄️",            "answer": "Brother Bear",                  "category": "movies",      "hook": "What movie is this?"},
    {"emojis": "🤖🌍💥",            "answer": "Transformers",                  "category": "movies",      "hook": "Name the movie!"},
    {"emojis": "👽🚲🌙",            "answer": "E.T.",                          "category": "movies",      "hook": "What movie is this?"},
    {"emojis": "🎭🃏😈",            "answer": "Joker",                         "category": "movies",      "hook": "Name the movie!"},
    {"emojis": "🦁👸🌅",            "answer": "Moana",                         "category": "movies",      "hook": "What movie is this?"},
    {"emojis": "🐉🧒🏮",            "answer": "Mulan",                         "category": "movies",      "hook": "Name the movie!"},
    {"emojis": "🌵🤠🏜️",            "answer": "Rango",                         "category": "movies",      "hook": "What movie is this?"},
    {"emojis": "🧊🏔️🐻",            "answer": "Ice Age",                       "category": "movies",      "hook": "Name the movie!"},
    {"emojis": "🐼🥋🏯",            "answer": "Kung Fu Panda",                 "category": "movies",      "hook": "What movie is this?"},
    {"emojis": "🐉🏔️🔥",            "answer": "How to Train Your Dragon",      "category": "movies",      "hook": "Name the movie!"},
    {"emojis": "🕷️🎤🎶",            "answer": "Sing",                          "category": "movies",      "hook": "What movie is this?"},
    {"emojis": "🧸🌟✨",            "answer": "Wish",                          "category": "movies",      "hook": "Name the movie!"},
    {"emojis": "🃏🎪🌀",            "answer": "The Greatest Showman",          "category": "movies",      "hook": "What movie is this?"},
    # ── SONGS ─────────────────────────────────────────────────────────────────
    {"emojis": "🎤👩🔥",            "answer": "Rolling in the Deep – Adele",   "category": "songs",       "hook": "Name the song!"},
    {"emojis": "🌊🏄‍♀️🎸",           "answer": "Good Vibrations – The Beach Boys","category": "songs",      "hook": "Name the song!"},
    {"emojis": "💃🕺🎶",            "answer": "Can't Stop the Feeling – Justin Timberlake","category":"songs","hook":"Name the song!"},
    {"emojis": "🎺🌃🎷",            "answer": "New York, New York – Frank Sinatra","category":"songs",     "hook": "Name the song!"},
    {"emojis": "🚀🌠👨‍🚀",           "answer": "Rocket Man – Elton John",       "category": "songs",       "hook": "Name the song!"},
    {"emojis": "🍋🐝🐍",            "answer": "Lemonade – Beyoncé",            "category": "songs",       "hook": "Name the song!"},
    {"emojis": "🎸💀🤘",            "answer": "Bohemian Rhapsody – Queen",     "category": "songs",       "hook": "Name the song!"},
    {"emojis": "☀️🌻😎",            "answer": "Here Comes the Sun – The Beatles","category":"songs",      "hook": "Name the song!"},
    {"emojis": "🌧️🌈☔",            "answer": "Singing in the Rain",           "category": "songs",       "hook": "Name the song!"},
    {"emojis": "🐍👠👗",            "answer": "Bad Blood – Taylor Swift",      "category": "songs",       "hook": "Name the song!"},
    {"emojis": "🔔🎄⛪",            "answer": "Jingle Bell Rock",              "category": "songs",       "hook": "Name the song!"},
    {"emojis": "🎵💫🌙",            "answer": "Moonlight Sonata – Beethoven",  "category": "songs",       "hook": "Name the song!"},
    {"emojis": "🦋🎤🌟",            "answer": "Butterfly – Mariah Carey",      "category": "songs",       "hook": "Name the song!"},
    {"emojis": "🏠🔥💔",            "answer": "Burning House – Cam",           "category": "songs",       "hook": "Name the song!"},
    {"emojis": "🌊🏖️🎸",            "answer": "Hotel California – Eagles",     "category": "songs",       "hook": "Name the song!"},
    {"emojis": "💍👸🎶",            "answer": "Single Ladies – Beyoncé",       "category": "songs",       "hook": "Name the song!"},
    {"emojis": "🎻😢🌹",            "answer": "My Heart Will Go On – Céline Dion","category":"songs",     "hook": "Name the song!"},
    {"emojis": "🐺🌕🎤",            "answer": "Hungry Like the Wolf – Duran Duran","category":"songs",   "hook": "Name the song!"},
    {"emojis": "🕶️🌴😎",            "answer": "Sunglasses at Night",           "category": "songs",       "hook": "Name the song!"},
    {"emojis": "🎹🌧️💧",            "answer": "November Rain – Guns N' Roses", "category": "songs",       "hook": "Name the song!"},
    {"emojis": "🎤🦅🌄",            "answer": "Eye of the Tiger – Survivor",   "category": "songs",       "hook": "Name the song!"},
    {"emojis": "🌍✋🤝",            "answer": "We Are the World",              "category": "songs",       "hook": "Name the song!"},
    {"emojis": "🕺🪩🌃",            "answer": "Stayin' Alive – Bee Gees",      "category": "songs",       "hook": "Name the song!"},
    {"emojis": "🎸🔥👊",            "answer": "Smells Like Teen Spirit – Nirvana","category":"songs",     "hook": "Name the song!"},
    {"emojis": "🌹🎤💃",            "answer": "La Vida Loca – Ricky Martin",   "category": "songs",       "hook": "Name the song!"},
    {"emojis": "🕊️✌️🎵",            "answer": "Imagine – John Lennon",         "category": "songs",       "hook": "Name the song!"},
    {"emojis": "🍎📱🎧",            "answer": "iSpy – KYLE",                   "category": "songs",       "hook": "Name the song!"},
    {"emojis": "🦁🌍❤️",            "answer": "Circle of Life – Elton John",   "category": "songs",       "hook": "Name the song!"},
    {"emojis": "🌊💨🏄",            "answer": "Surfin' USA – The Beach Boys",  "category": "songs",       "hook": "Name the song!"},
    {"emojis": "🌙⭐🎶",            "answer": "Fly Me to the Moon – Frank Sinatra","category":"songs",    "hook": "Name the song!"},
    # ── COUNTRIES ─────────────────────────────────────────────────────────────
    {"emojis": "🇧🇷🌴⚽",            "answer": "Brazil",                        "category": "countries",   "hook": "Which country?"},
    {"emojis": "🇯🇵🗻🌸",            "answer": "Japan",                         "category": "countries",   "hook": "Which country?"},
    {"emojis": "🇮🇳🕌🌶️",            "answer": "India",                         "category": "countries",   "hook": "Which country?"},
    {"emojis": "🇮🇹🍕🏛️",            "answer": "Italy",                         "category": "countries",   "hook": "Which country?"},
    {"emojis": "🇨🇳🐉🥢",            "answer": "China",                         "category": "countries",   "hook": "Which country?"},
    {"emojis": "🇫🇷🗼🥐",            "answer": "France",                        "category": "countries",   "hook": "Which country?"},
    {"emojis": "🇦🇺🦘🪃",            "answer": "Australia",                     "category": "countries",   "hook": "Which country?"},
    {"emojis": "🇰🇷🎎🥡",            "answer": "South Korea",                   "category": "countries",   "hook": "Which country?"},
    {"emojis": "🇪🇬🏺🐪",            "answer": "Egypt",                         "category": "countries",   "hook": "Which country?"},
    {"emojis": "🇲🇽🌮🎺",            "answer": "Mexico",                        "category": "countries",   "hook": "Which country?"},
    {"emojis": "🇷🇺❄️🐻",            "answer": "Russia",                        "category": "countries",   "hook": "Which country?"},
    {"emojis": "🇬🇧👑☕",            "answer": "United Kingdom",                "category": "countries",   "hook": "Which country?"},
    {"emojis": "🇺🇸🗽🦅",            "answer": "USA",                           "category": "countries",   "hook": "Which country?"},
    {"emojis": "🇨🇦🍁🏒",            "answer": "Canada",                        "category": "countries",   "hook": "Which country?"},
    {"emojis": "🇿🇦🦁🌍",            "answer": "South Africa",                  "category": "countries",   "hook": "Which country?"},
    {"emojis": "🇸🇦🕌🛢️",            "answer": "Saudi Arabia",                  "category": "countries",   "hook": "Which country?"},
    {"emojis": "🇦🇷🥩💃",            "answer": "Argentina",                     "category": "countries",   "hook": "Which country?"},
    {"emojis": "🇳🇴🌊🎿",            "answer": "Norway",                        "category": "countries",   "hook": "Which country?"},
    {"emojis": "🇹🇭🐘🍜",            "answer": "Thailand",                      "category": "countries",   "hook": "Which country?"},
    {"emojis": "🇬🇷🏛️🫒",            "answer": "Greece",                        "category": "countries",   "hook": "Which country?"},
    {"emojis": "🇹🇷🌙⭐🍢",           "answer": "Turkey",                        "category": "countries",   "hook": "Which country?"},
    {"emojis": "🇮🇩🌴🏄",            "answer": "Indonesia",                     "category": "countries",   "hook": "Which country?"},
    {"emojis": "🇵🇹🐟🍷",            "answer": "Portugal",                      "category": "countries",   "hook": "Which country?"},
    {"emojis": "🇵🇪🦙🏔️",            "answer": "Peru",                          "category": "countries",   "hook": "Which country?"},
    {"emojis": "🇸🇪👱🏔️",            "answer": "Sweden",                        "category": "countries",   "hook": "Which country?"},
    # ── BRANDS ────────────────────────────────────────────────────────────────
    {"emojis": "🍎💻📱",            "answer": "Apple",                          "category": "brands",      "hook": "Name the brand!"},
    {"emojis": "🔴▶️🎬",            "answer": "Netflix",                       "category": "brands",      "hook": "Name the brand!"},
    {"emojis": "🍔🍟👑",            "answer": "Burger King",                   "category": "brands",      "hook": "Name the brand!"},
    {"emojis": "☕🧜‍♀️🟢",           "answer": "Starbucks",                     "category": "brands",      "hook": "Name the brand!"},
    {"emojis": "🔵👍📘",            "answer": "Facebook",                      "category": "brands",      "hook": "Name the brand!"},
    {"emojis": "🔍🌐💡",            "answer": "Google",                        "category": "brands",      "hook": "Name the brand!"},
    {"emojis": "🛒📦🔶",            "answer": "Amazon",                        "category": "brands",      "hook": "Name the brand!"},
    {"emojis": "👟✔️🏃",            "answer": "Nike",                          "category": "brands",      "hook": "Name the brand!"},
    {"emojis": "🦁🌊🎢",            "answer": "Disney",                        "category": "brands",      "hook": "Name the brand!"},
    {"emojis": "🍕🛵⏱️",            "answer": "Domino's",                      "category": "brands",      "hook": "Name the brand!"},
    {"emojis": "🐦🔵💬",            "answer": "Twitter / X",                   "category": "brands",      "hook": "Name the brand!"},
    {"emojis": "📸🎞️🟣",            "answer": "Instagram",                     "category": "brands",      "hook": "Name the brand!"},
    {"emojis": "🚗⚡🔋",            "answer": "Tesla",                         "category": "brands",      "hook": "Name the brand!"},
    {"emojis": "🛻🌍♻️",            "answer": "Toyota",                        "category": "brands",      "hook": "Name the brand!"},
    {"emojis": "🎮🕹️🟢",            "answer": "Xbox",                          "category": "brands",      "hook": "Name the brand!"},
    {"emojis": "🎮🔵❎",            "answer": "PlayStation",                   "category": "brands",      "hook": "Name the brand!"},
    {"emojis": "🎵🎶🟢",            "answer": "Spotify",                       "category": "brands",      "hook": "Name the brand!"},
    {"emojis": "🚀🛸👨‍💼",           "answer": "SpaceX",                        "category": "brands",      "hook": "Name the brand!"},
    {"emojis": "💬🟢📲",            "answer": "WhatsApp",                      "category": "brands",      "hook": "Name the brand!"},
    {"emojis": "🎥📹🔴",            "answer": "YouTube",                       "category": "brands",      "hook": "Name the brand!"},
    {"emojis": "🍫🐄🥛",            "answer": "Cadbury",                       "category": "brands",      "hook": "Name the brand!"},
    {"emojis": "🥤🔴⚫",            "answer": "Coca-Cola",                     "category": "brands",      "hook": "Name the brand!"},
    {"emojis": "🥤🔵⚪",            "answer": "Pepsi",                         "category": "brands",      "hook": "Name the brand!"},
    {"emojis": "🐊👜💚",            "answer": "Lacoste",                       "category": "brands",      "hook": "Name the brand!"},
    {"emojis": "✈️🟣💼",            "answer": "FedEx",                         "category": "brands",      "hook": "Name the brand!"},
    # ── PHRASES ───────────────────────────────────────────────────────────────
    {"emojis": "🌧️🌈🌤️",            "answer": "Every cloud has a silver lining","category": "phrases",    "hook": "Guess the phrase!"},
    {"emojis": "🐦🪱⏰",            "answer": "The early bird catches the worm","category": "phrases",     "hook": "Guess the phrase!"},
    {"emojis": "🐕💤😴",            "answer": "Let sleeping dogs lie",         "category": "phrases",     "hook": "Guess the phrase!"},
    {"emojis": "🪣❄️💧",            "answer": "Kick the bucket",               "category": "phrases",     "hook": "Guess the phrase!"},
    {"emojis": "🐠🌊🌀",            "answer": "A fish out of water",           "category": "phrases",     "hook": "Guess the phrase!"},
    {"emojis": "🐄💀🐄",            "answer": "Sacred cow",                    "category": "phrases",     "hook": "Guess the phrase!"},
    {"emojis": "🏠🔑❤️",            "answer": "Home is where the heart is",    "category": "phrases",     "hook": "Guess the phrase!"},
    {"emojis": "🌙✨💤",            "answer": "Once in a blue moon",           "category": "phrases",     "hook": "Guess the phrase!"},
    {"emojis": "🐎🎁👄",            "answer": "Don't look a gift horse in the mouth","category":"phrases","hook": "Guess the phrase!"},
    {"emojis": "🪨🌊🗡️",            "answer": "Between a rock and a hard place","category": "phrases",    "hook": "Guess the phrase!"},
    {"emojis": "🎂🍰🎉",            "answer": "A piece of cake",               "category": "phrases",     "hook": "Guess the phrase!"},
    {"emojis": "🍋🍹😊",            "answer": "When life gives you lemons",    "category": "phrases",     "hook": "Guess the phrase!"},
    {"emojis": "🐘🏠👀",            "answer": "Elephant in the room",          "category": "phrases",     "hook": "Guess the phrase!"},
    {"emojis": "🪡🧵👁️",            "answer": "Eye of the needle",             "category": "phrases",     "hook": "Guess the phrase!"},
    {"emojis": "🌊🏊💪",            "answer": "Sink or swim",                  "category": "phrases",     "hook": "Guess the phrase!"},
    {"emojis": "🐓🥚❓",            "answer": "Which came first, the chicken or the egg","category":"phrases","hook":"Guess the phrase!"},
    {"emojis": "🐛🦋✨",            "answer": "Transformation",                "category": "phrases",     "hook": "Guess the phrase!"},
    {"emojis": "🔥💧🌊",            "answer": "Fight fire with fire",          "category": "phrases",     "hook": "Guess the phrase!"},
    {"emojis": "🧠🔐💡",            "answer": "Pick someone's brain",          "category": "phrases",     "hook": "Guess the phrase!"},
    {"emojis": "🎯🎳💯",            "answer": "Hit the nail on the head",      "category": "phrases",     "hook": "Guess the phrase!"},
    # ── SPORTS ────────────────────────────────────────────────────────────────
    {"emojis": "🏀🐦🌆",            "answer": "Atlanta Hawks",                 "category": "sports",      "hook": "Name the team!"},
    {"emojis": "🐻🏈🌉",            "answer": "Chicago Bears",                 "category": "sports",      "hook": "Name the team!"},
    {"emojis": "🦅🏈🇺🇸",           "answer": "Philadelphia Eagles",           "category": "sports",      "hook": "Name the team!"},
    {"emojis": "🥊👊🏆",            "answer": "Muhammad Ali",                  "category": "sports",      "hook": "Name the athlete!"},
    {"emojis": "⚽🐐🇦🇷",           "answer": "Lionel Messi",                  "category": "sports",      "hook": "Name the athlete!"},
    {"emojis": "🎾🐐🇷🇸",           "answer": "Novak Djokovic",                "category": "sports",      "hook": "Name the athlete!"},
    {"emojis": "🏀🐐🇺🇸",           "answer": "LeBron James",                  "category": "sports",      "hook": "Name the athlete!"},
    {"emojis": "🏊‍♂️🥇🎖️",           "answer": "Michael Phelps",               "category": "sports",      "hook": "Name the athlete!"},
    {"emojis": "⚽🏆🇧🇷",           "answer": "Ronaldo",                       "category": "sports",      "hook": "Name the athlete!"},
    {"emojis": "🏋️‍♀️🌍💪",           "answer": "Simone Biles",                 "category": "sports",      "hook": "Name the athlete!"},
    {"emojis": "🎾🏆🐐",            "answer": "Roger Federer",                 "category": "sports",      "hook": "Name the athlete!"},
    {"emojis": "🏈🐐🇺🇸",           "answer": "Tom Brady",                     "category": "sports",      "hook": "Name the athlete!"},
    {"emojis": "⚡🏃‍♂️🇯🇲",           "answer": "Usain Bolt",                   "category": "sports",      "hook": "Name the athlete!"},
    {"emojis": "🏒🐐🇨🇦",           "answer": "Wayne Gretzky",                 "category": "sports",      "hook": "Name the athlete!"},
    {"emojis": "⛳🐐🇺🇸",            "answer": "Tiger Woods",                   "category": "sports",      "hook": "Name the athlete!"},
    {"emojis": "🏀🐐🇺🇸🐐",          "answer": "Michael Jordan",                "category": "sports",      "hook": "Name the athlete!"},
    # ── CELEBRITIES ───────────────────────────────────────────────────────────
    {"emojis": "👑🎤🇺🇸",           "answer": "Elvis Presley",                 "category": "celebrities", "hook": "Name the celebrity!"},
    {"emojis": "🎤💃🐝",            "answer": "Beyoncé",                       "category": "celebrities", "hook": "Name the celebrity!"},
    {"emojis": "🕶️🎸🔴",            "answer": "Bono",                          "category": "celebrities", "hook": "Name the celebrity!"},
    {"emojis": "🎤🧣🇬🇧",           "answer": "Adele",                         "category": "celebrities", "hook": "Name the celebrity!"},
    {"emojis": "🎤👄💄",            "answer": "Lady Gaga",                     "category": "celebrities", "hook": "Name the celebrity!"},
    {"emojis": "🎤🐊🟢",            "answer": "Ed Sheeran",                    "category": "celebrities", "hook": "Name the celebrity!"},
    {"emojis": "🐍👗🎤",            "answer": "Taylor Swift",                  "category": "celebrities", "hook": "Name the celebrity!"},
    {"emojis": "🌙🎤🕺",            "answer": "Michael Jackson",               "category": "celebrities", "hook": "Name the celebrity!"},
    {"emojis": "🎤🦈🇦🇺",           "answer": "Iggy Azalea",                   "category": "celebrities", "hook": "Name the celebrity!"},
    {"emojis": "🎤🔥🇨🇦",           "answer": "Drake",                         "category": "celebrities", "hook": "Name the celebrity!"},
    {"emojis": "🎤🌊🇺🇸",           "answer": "Eminem",                        "category": "celebrities", "hook": "Name the celebrity!"},
    {"emojis": "🎤🌹🎸",            "answer": "Axl Rose",                      "category": "celebrities", "hook": "Name the celebrity!"},
    {"emojis": "👑🦋🎶",            "answer": "Mariah Carey",                  "category": "celebrities", "hook": "Name the celebrity!"},
    # ── TV SHOWS ──────────────────────────────────────────────────────────────
    {"emojis": "🧪👨‍🔬💀",           "answer": "Breaking Bad",                  "category": "tv_shows",    "hook": "Name the show!"},
    {"emojis": "🐉🗡️👑",            "answer": "Game of Thrones",               "category": "tv_shows",    "hook": "Name the show!"},
    {"emojis": "🏢😅💼",            "answer": "The Office",                    "category": "tv_shows",    "hook": "Name the show!"},
    {"emojis": "👨‍👩‍👧‍👦🏠😂",          "answer": "Modern Family",                 "category": "tv_shows",    "hook": "Name the show!"},
    {"emojis": "🕵️‍♂️🔍🧬",           "answer": "CSI",                           "category": "tv_shows",    "hook": "Name the show!"},
    {"emojis": "🧟‍♂️🌍💀",           "answer": "The Walking Dead",              "category": "tv_shows",    "hook": "Name the show!"},
    {"emojis": "🏥👨‍⚕️💉",            "answer": "Grey's Anatomy",                "category": "tv_shows",    "hook": "Name the show!"},
    {"emojis": "🛋️☕🗽",            "answer": "Friends",                       "category": "tv_shows",    "hook": "Name the show!"},
    {"emojis": "🌀🚪🔮",            "answer": "Stranger Things",               "category": "tv_shows",    "hook": "Name the show!"},
    {"emojis": "🤵🍸🔫",            "answer": "James Bond",                    "category": "tv_shows",    "hook": "Name the show!"},
    {"emojis": "🎸🏫🎤",            "answer": "Glee",                          "category": "tv_shows",    "hook": "Name the show!"},
    {"emojis": "🦁🌍🔬",            "answer": "Planet Earth",                  "category": "tv_shows",    "hook": "Name the show!"},
    {"emojis": "🍳🍽️⭐",            "answer": "MasterChef",                    "category": "tv_shows",    "hook": "Name the show!"},
    {"emojis": "💰🤑🎰",            "answer": "Who Wants to Be a Millionaire", "category": "tv_shows",    "hook": "Name the show!"},
    {"emojis": "🌮🧑‍🍳🌎",           "answer": "Taco Chronicles",               "category": "tv_shows",    "hook": "Name the show!"},
    {"emojis": "🎤🪑🏆",            "answer": "American Idol",                 "category": "tv_shows",    "hook": "Name the show!"},
    {"emojis": "🌊🏝️🌺",            "answer": "Lost",                          "category": "tv_shows",    "hook": "Name the show!"},
    {"emojis": "🤖🧠🌐",            "answer": "Westworld",                     "category": "tv_shows",    "hook": "Name the show!"},
    {"emojis": "🦸‍♂️⚡🧤",           "answer": "The Flash",                     "category": "tv_shows",    "hook": "Name the show!"},
    {"emojis": "🏹🌲🦉",            "answer": "Arrow",                         "category": "tv_shows",    "hook": "Name the show!"},
    {"emojis": "🐉🤴⚔️",            "answer": "Merlin",                        "category": "tv_shows",    "hook": "Name the show!"},
    # ── FOOD ──────────────────────────────────────────────────────────────────
    {"emojis": "🍣🐟🍚",            "answer": "Sushi",                         "category": "food",        "hook": "What food is this?"},
    {"emojis": "🫓🧀🍅",            "answer": "Bruschetta",                    "category": "food",        "hook": "What food is this?"},
    {"emojis": "🥑🍋🧄",            "answer": "Guacamole",                     "category": "food",        "hook": "What food is this?"},
    {"emojis": "🍜🥚🌶️",            "answer": "Ramen",                         "category": "food",        "hook": "What food is this?"},
    {"emojis": "🥟🥬🍖",            "answer": "Dumplings",                     "category": "food",        "hook": "What food is this?"},
    {"emojis": "🧇🍓🍯",            "answer": "Waffles",                       "category": "food",        "hook": "What food is this?"},
    {"emojis": "🥗🫒🧀",            "answer": "Greek Salad",                   "category": "food",        "hook": "What food is this?"},
    {"emojis": "🫔🥩🌶️",            "answer": "Burrito",                       "category": "food",        "hook": "What food is this?"},
    {"emojis": "🍲🧅🥕",            "answer": "Beef Stew",                     "category": "food",        "hook": "What food is this?"},
    {"emojis": "🍮🥛🍬",            "answer": "Crème Brûlée",                  "category": "food",        "hook": "What food is this?"},
    {"emojis": "🥐☕🧈",            "answer": "Croissant",                     "category": "food",        "hook": "What food is this?"},
    {"emojis": "🦞🧈🍋",            "answer": "Lobster Bisque",                "category": "food",        "hook": "What food is this?"},
    {"emojis": "🍛🥥🍗",            "answer": "Coconut Curry",                 "category": "food",        "hook": "What food is this?"},
    {"emojis": "🥞🍁🧇",            "answer": "Pancakes",                      "category": "food",        "hook": "What food is this?"},
    {"emojis": "🫕🥩🌿",            "answer": "Hot Pot",                       "category": "food",        "hook": "What food is this?"},
    {"emojis": "🐙🍋🧄",            "answer": "Calamari",                      "category": "food",        "hook": "What food is this?"},
    {"emojis": "🥪🥑🍗",            "answer": "Chicken Avocado Sandwich",      "category": "food",        "hook": "What food is this?"},
    {"emojis": "🍡🍵🌸",            "answer": "Mochi",                         "category": "food",        "hook": "What food is this?"},
    {"emojis": "🧆🥙🌿",            "answer": "Falafel",                       "category": "food",        "hook": "What food is this?"},
    {"emojis": "🫙🍓🍞",            "answer": "Jam on Toast",                  "category": "food",        "hook": "What food is this?"},
    # ── BOOKS ─────────────────────────────────────────────────────────────────
    {"emojis": "🧙‍♂️🏫✉️",            "answer": "Harry Potter",                  "category": "books",       "hook": "Name the book!"},
    {"emojis": "💍🗡️🌋",            "answer": "The Lord of the Rings",         "category": "books",       "hook": "Name the book!"},
    {"emojis": "🦁🧥🪄",            "answer": "The Lion, the Witch & the Wardrobe","category":"books",     "hook": "Name the book!"},
    {"emojis": "🕷️🌡️🏡",            "answer": "Charlotte's Web",               "category": "books",       "hook": "Name the book!"},
    {"emojis": "🐛🎩🍄",            "answer": "Alice in Wonderland",           "category": "books",       "hook": "Name the book!"},
    {"emojis": "🐋🚢⚔️",            "answer": "Moby Dick",                     "category": "books",       "hook": "Name the book!"},
    {"emojis": "👓🌾🚜",            "answer": "To Kill a Mockingbird",         "category": "books",       "hook": "Name the book!"},
    {"emojis": "🔭🌙🪐",            "answer": "The Little Prince",             "category": "books",       "hook": "Name the book!"},
    {"emojis": "🐷🐺🏠",            "answer": "The Three Little Pigs",         "category": "books",       "hook": "Name the book!"},
    {"emojis": "🐰⏱️🃏",            "answer": "Alice in Wonderland",           "category": "books",       "hook": "Name the book!"},
    {"emojis": "🐢🐇🏁",            "answer": "The Tortoise and the Hare",     "category": "books",       "hook": "Name the book!"},
    {"emojis": "🦁🐅🌿",            "answer": "The Jungle Book",               "category": "books",       "hook": "Name the book!"},
    {"emojis": "👤🔭📘",            "answer": "1984 – George Orwell",          "category": "books",       "hook": "Name the book!"},
    {"emojis": "🐦🌊🗺️",            "answer": "Treasure Island",               "category": "books",       "hook": "Name the book!"},
    {"emojis": "🧪🌙🏡",            "answer": "Frankenstein",                  "category": "books",       "hook": "Name the book!"},
    {"emojis": "🦸📚🌍",            "answer": "Around the World in 80 Days",   "category": "books",       "hook": "Name the book!"},
    {"emojis": "🏹🌲🏹",            "answer": "The Hunger Games",              "category": "books",       "hook": "Name the book!"},
    {"emojis": "💔📝🌹",            "answer": "Romeo and Juliet",              "category": "books",       "hook": "Name the book!"},
    {"emojis": "🌊🏖️🌅",            "answer": "The Old Man and the Sea",       "category": "books",       "hook": "Name the book!"},
    {"emojis": "🕵️‍♂️🔎💀",           "answer": "Sherlock Holmes",               "category": "books",       "hook": "Name the book!"},
    # ── ADDITIONAL COUNTRIES ──────────────────────────────────────────────────
    {"emojis": "🇳🇿🐑🌋",            "answer": "New Zealand",                   "category": "countries",   "hook": "Which country?"},
    {"emojis": "🇸🇬🦁🌆",            "answer": "Singapore",                     "category": "countries",   "hook": "Which country?"},
    {"emojis": "🇳🇬🥁🌍",            "answer": "Nigeria",                       "category": "countries",   "hook": "Which country?"},
    {"emojis": "🇨🇴☕🌸",            "answer": "Colombia",                      "category": "countries",   "hook": "Which country?"},
    {"emojis": "🇵🇭🌴🏄",            "answer": "Philippines",                   "category": "countries",   "hook": "Which country?"},
    {"emojis": "🇮🇱🕎🕌",            "answer": "Israel",                        "category": "countries",   "hook": "Which country?"},
    {"emojis": "🇨🇿🏰🍺",            "answer": "Czech Republic",                "category": "countries",   "hook": "Which country?"},
    {"emojis": "🇭🇺🌶️🏰",            "answer": "Hungary",                       "category": "countries",   "hook": "Which country?"},
    {"emojis": "🇵🇱🦅🥟",            "answer": "Poland",                        "category": "countries",   "hook": "Which country?"},
    {"emojis": "🇰🇪🦒🌅",            "answer": "Kenya",                         "category": "countries",   "hook": "Which country?"},
    {"emojis": "🇲🇦🕌🌴",            "answer": "Morocco",                       "category": "countries",   "hook": "Which country?"},
    {"emojis": "🇻🇳🍜🌿",            "answer": "Vietnam",                       "category": "countries",   "hook": "Which country?"},
    # ── ADDITIONAL CELEBRITIES ────────────────────────────────────────────────
    {"emojis": "🎤🦋🎶",            "answer": "Shakira",                       "category": "celebrities", "hook": "Name the celebrity!"},
    {"emojis": "🎤🌹🇵🇷",           "answer": "Bad Bunny",                     "category": "celebrities", "hook": "Name the celebrity!"},
    {"emojis": "🎤👒🇦🇺",           "answer": "Kylie Minogue",                 "category": "celebrities", "hook": "Name the celebrity!"},
    {"emojis": "🎤🦅🇺🇸",           "answer": "Jennifer Lopez",                "category": "celebrities", "hook": "Name the celebrity!"},
    {"emojis": "🎤⚡🇬🇧",           "answer": "David Bowie",                   "category": "celebrities", "hook": "Name the celebrity!"},
    {"emojis": "🎤🌙🇺🇸",           "answer": "Billie Eilish",                 "category": "celebrities", "hook": "Name the celebrity!"},
    {"emojis": "🎤🔥🌍",            "answer": "Burna Boy",                     "category": "celebrities", "hook": "Name the celebrity!"},
    {"emojis": "🎤🎹🇷🇺",           "answer": "Tchaikovsky",                   "category": "celebrities", "hook": "Name the celebrity!"},
    {"emojis": "🎤🏆🇺🇸",           "answer": "Kendrick Lamar",                "category": "celebrities", "hook": "Name the celebrity!"},
    # ── ADDITIONAL FOOD ───────────────────────────────────────────────────────
    {"emojis": "🥩🌽🔥",            "answer": "BBQ Corn on the Cob",          "category": "food",        "hook": "What food is this?"},
    {"emojis": "🍝🧅🍅",            "answer": "Bolognese",                     "category": "food",        "hook": "What food is this?"},
    {"emojis": "🧋🧊🍵",            "answer": "Bubble Tea",                    "category": "food",        "hook": "What food is this?"},
    {"emojis": "🥑🍞🥚",            "answer": "Avocado Toast with Egg",       "category": "food",        "hook": "What food is this?"},
    {"emojis": "🍕🍍🐖",            "answer": "Hawaiian Pizza",                "category": "food",        "hook": "What food is this?"},
    {"emojis": "🌽🧀🧈",            "answer": "Elote",                         "category": "food",        "hook": "What food is this?"},
    {"emojis": "🍩🍫☕",            "answer": "Chocolate Doughnut",            "category": "food",        "hook": "What food is this?"},
    {"emojis": "🐟🍋🧄",            "answer": "Fish and Chips",                "category": "food",        "hook": "What food is this?"},
    {"emojis": "🦐🍚🌶️",            "answer": "Prawn Fried Rice",              "category": "food",        "hook": "What food is this?"},
    {"emojis": "🍠🥥🍚",            "answer": "Sweet Potato Coconut Rice",     "category": "food",        "hook": "What food is this?"},
    # ── ADDITIONAL BOOKS ──────────────────────────────────────────────────────
    {"emojis": "🧑‍🔬⚗️🌙",            "answer": "The Strange Case of Dr Jekyll and Mr Hyde","category":"books","hook":"Name the book!"},
    {"emojis": "💣🌍🕊️",            "answer": "War and Peace",                 "category": "books",       "hook": "Name the book!"},
    {"emojis": "🌊🏝️🗺️",            "answer": "Robinson Crusoe",               "category": "books",       "hook": "Name the book!"},
    {"emojis": "🎩🔮🕵️",            "answer": "The Great Gatsby",              "category": "books",       "hook": "Name the book!"},
    {"emojis": "🐉🏰🗡️",            "answer": "Eragon",                        "category": "books",       "hook": "Name the book!"},
    {"emojis": "🧠🔬🌍",            "answer": "A Brief History of Time",       "category": "books",       "hook": "Name the book!"},
    {"emojis": "🔥🌾📖",            "answer": "The Kite Runner",               "category": "books",       "hook": "Name the book!"},
    {"emojis": "💌📬🌍",            "answer": "The Diary of a Young Girl",     "category": "books",       "hook": "Name the book!"},
    {"emojis": "🌹❄️📖",            "answer": "The Secret Garden",             "category": "books",       "hook": "Name the book!"},
    # ── EXTRA ─────────────────────────────────────────────────────────────────
    {"emojis": "🌊💔🎤",            "answer": "Someone Like You – Adele",      "category": "songs",       "hook": "Name the song!"},
    {"emojis": "🌙💜🎤",            "answer": "Blinding Lights – The Weeknd",  "category": "songs",       "hook": "Name the song!"},
]


def build_items(raw_list, start_id):
    items = []
    for i, raw in enumerate(raw_list):
        num = start_id + i
        item = {
            "id": f"eq_{num:04d}",
            "emojis": raw["emojis"],
            "answer": raw["answer"],
            "category": raw["category"],
            "hook": raw["hook"],
        }
        items.append(item)
    return items


def main():
    path = Path(__file__).parent / "emojiquiz" / "questions.json"
    data = json.loads(path.read_text(encoding="utf-8"))

    new_items = build_items(NEW_ITEMS_RAW, start_id=281)

    if len(new_items) != 272:
        raise ValueError(f"Expected 272 items, got {len(new_items)}")

    data.extend(new_items)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"Done. Total items: {len(data)}. New items added: {len(new_items)}.")
    print(f"ID range: {new_items[0]['id']} – {new_items[-1]['id']}")


if __name__ == "__main__":
    main()
