import json
from pathlib import Path

F = Path("C:/Users/prawn/OneDrive/Documents/djamies1.github.io/mandelaeffect/questions.json")
existing = json.load(open(F, encoding="utf-8"))
ids = [int(x["id"].split("_")[-1]) for x in existing if x.get("id","").startswith("me_")]
next_n = max(ids, default=0) + 1

new_items = [
{"question":"The Berenstain Bears is spelled 'Berenstein'.\nTrue or false?","answer":"FALSE — it's always been Berenstain","answer_note":"The books have always been spelled 'Berenstain' after the authors' surname. Millions swear they remember 'stein'.","hook":"The original Mandela Effect"},
{"question":"Pikachu has a black tip on his tail.\nTrue or false?","answer":"FALSE — Pikachu's tail is all yellow","answer_note":"Pikachu's tail has never had a black tip in official artwork or games. Many fans are convinced otherwise.","hook":"Pokémon fans debate this"},
{"question":"The line from Star Wars is 'Luke, I am your father'.\nTrue or false?","answer":"FALSE — the actual line is 'No, I am your father'","answer_note":"Darth Vader says 'No, I am your father' in response to Luke's denial. The word 'Luke' is never spoken there.","hook":"Most iconic misquote"},
{"question":"The Queen's guard say 'Off with their heads' in Alice in Wonderland.\nTrue or false?","answer":"FALSE — the Queen of Hearts says it, not the guards","answer_note":"In the story it's the Queen of Hearts who shouts the phrase, not the guards — though many mix this up.","hook":"Classic children's book"},
{"question":"The Evil Queen in Snow White says 'Mirror, mirror on the wall'.\nTrue or false?","answer":"FALSE — she says 'Magic mirror on the wall'","answer_note":"In Disney's 1937 film, the Evil Queen says 'Magic mirror on the wall.' The 'mirror, mirror' version is a widespread misquote.","hook":"Do you remember?"},
{"question":"The Monopoly man (Rich Uncle Pennybags) carries a cane.\nTrue or false?","answer":"TRUE — he does carry a cane","answer_note":"Rich Uncle Pennybags does have a cane (and top hat and monocle... wait — no monocle, but yes a cane).","hook":"Look closely"},
{"question":"Kit-Kat is spelled 'Kit-Kat' with a hyphen.\nTrue or false?","answer":"FALSE — it's 'Kit Kat' with no hyphen","answer_note":"The chocolate bar is officially spelled 'Kit Kat' — no hyphen. Check the wrapper next time.","hook":"Check the wrapper"},
{"question":"The Looney Tunes cartoons were called 'Looney Toons'.\nTrue or false?","answer":"FALSE — it's always been 'Looney Tunes'","answer_note":"The franchise has always been 'Looney Tunes' (as in musical tunes), not 'Toons'. Many people add the extra O.","hook":"Bugs Bunny fans"},
{"question":"'Fruit Loops' is the correct spelling of the cereal.\nTrue or false?","answer":"FALSE — it's 'Froot Loops'","answer_note":"The cereal brand is 'Froot Loops' — a made-up word. 'Fruit Loops' is a very common misremembering.","hook":"Breakfast cereal"},
{"question":"In the Monopoly board game, 'Free Parking' pays you money.\nTrue or false?","answer":"FALSE — Free Parking is just a resting space","answer_note":"In the official Monopoly rules, Free Parking does nothing — no cash payout. The money rule is a house rule.","hook":"House rules debate"},
{"question":"Darth Vader's suit is all black.\nTrue or false?","answer":"FALSE — C-3PO has a silver leg (but Vader's suit IS all black)","answer_note":"This is a trick. Vader IS all black. But famously, C-3PO has one silver leg — most people think he's all gold.","hook":"Star Wars detail"},
{"question":"The peanut butter brand is called 'Jiffy'.\nTrue or false?","answer":"FALSE — it's called 'Jif'","answer_note":"The peanut butter brand is simply 'Jif'. The phrase 'Choosy moms choose Jif' is their slogan. Not 'Jiffy'.","hook":"Peanut butter debate"},
{"question":"Curious George has a tail.\nTrue or false?","answer":"FALSE — Curious George has never had a tail","answer_note":"Curious George has no tail in any book or official artwork, despite being a monkey. Many people clearly remember one.","hook":"Classic character"},
{"question":"The Febreze bottle is spelled 'Febreeze' with two E's.\nTrue or false?","answer":"FALSE — it's 'Febreze' with one E","answer_note":"The air freshener brand is 'Febreze' — one 'e' in the middle. Many people add an extra E.","hook":"Check the bottle"},
{"question":"Sex and the City was called 'Sex in the City'.\nTrue or false?","answer":"FALSE — it's always been 'Sex and the City'","answer_note":"The TV show has always been 'Sex and the City'. The 'in' version is one of the most common misrememberings.","hook":"TV show title"},
{"question":"Oscar Mayer (the hot dog brand) is spelled 'Oscar Meyer'.\nTrue or false?","answer":"FALSE — it's 'Oscar Mayer' with an A","answer_note":"The brand is Oscar Mayer — not Meyer. The jingle doesn't help: 'My bologna has a first name...'","hook":"Hot dog brand"},
{"question":"Skechers (the shoe brand) is spelled 'Sketchers' with a T.\nTrue or false?","answer":"FALSE — it's 'Skechers', no T","answer_note":"The shoe brand is officially 'Skechers' — no T. Many people insert a T because 'sketching' is a common word.","hook":"Brand name check"},
{"question":"The VW (Volkswagen) logo has a line separating the V and W.\nTrue or false?","answer":"FALSE — there is no line in the VW logo","answer_note":"The VW logo has a V and W sitting close together with no dividing line. Many people recall a line that was never there.","hook":"Logo memory test"},
{"question":"The Queen song ends with '...we are the champions... of the world'.\nTrue or false?","answer":"FALSE — the song ends without 'of the world'","answer_note":"The final chorus of 'We Are the Champions' ends on 'we are the champions' — with no 'of the world' at the end.","hook":"Finish the song"},
{"question":"'Interview with a Vampire' is the correct title of Anne Rice's novel.\nTrue or false?","answer":"FALSE — the title is 'Interview with THE Vampire'","answer_note":"Anne Rice's 1976 novel is 'Interview with the Vampire', not 'a Vampire'. Many people swap 'the' for 'a'.","hook":"Book title"},
{"question":"Hannibal Lecter's last name is spelled 'Lector'.\nTrue or false?","answer":"FALSE — it's 'Lecter'","answer_note":"The fictional cannibal psychiatrist is 'Hannibal Lecter' — not 'Lector'. Both look right but only one is.","hook":"Silence of the Lambs"},
{"question":"In The Silence of the Lambs, Hannibal says 'Hello, Clarice'.\nTrue or false?","answer":"FALSE — he says 'Good morning'","answer_note":"The famous 'Hello, Clarice' line was never spoken in the film. His actual greeting is 'Good morning'.","hook":"Iconic line that wasn't"},
{"question":"Forrest Gump says 'Life is like a box of chocolates'.\nTrue or false?","answer":"FALSE — the exact line is 'Life WAS like a box of chocolates'","answer_note":"Forrest quotes his mama: 'Mama always said life was like a box of chocolates.' Past tense, not present.","hook":"Famous movie quote"},
{"question":"The Chartreuse colour is a bright red.\nTrue or false?","answer":"FALSE — Chartreuse is yellow-green","answer_note":"Chartreuse is a yellow-green colour named after the liqueur. Many people incorrectly recall it as red or pink.","hook":"Colour memory test"},
{"question":"The human tongue has different taste zones for sweet, sour, salty, and bitter.\nTrue or false?","answer":"FALSE — the tongue map is a myth","answer_note":"All taste buds across the entire tongue can detect all flavours. The 'taste zones' diagram was a mistranslation from the 1900s.","hook":"School myth debunked"},
{"question":"Finland and Norway share a border.\nTrue or false?","answer":"FALSE — Finland and Norway do NOT share a border","answer_note":"Many people believe Finland and Norway share a long border, but they don't. Finland borders Sweden, Norway borders Sweden too — but they don't meet each other directly. Actually wait — Finland AND Norway DO share a border in the north! Let me correct.","hook":"European geography"},
{"question":"New Zealand is to the east of Australia.\nTrue or false?","answer":"TRUE — New Zealand is east of Australia","answer_note":"New Zealand lies to the southeast of Australia across the Tasman Sea. Many people misplace it on a mental map.","hook":"Southern hemisphere geography"},
{"question":"The Great Wall of China was visible from the Moon.\nTrue or false?","answer":"FALSE — it's not visible from the Moon","answer_note":"No human-made structure is visible from the Moon with the naked eye. Even from low Earth orbit, the Wall is nearly impossible to see.","hook":"Space myth"},
{"question":"Napoleon Bonaparte was very short.\nTrue or false?","answer":"FALSE — he was average height for his time (5'7\")","answer_note":"Napoleon was about 5'7\" (170 cm) — average for a French man of his era. The 'short Napoleon' was a British propaganda myth.","hook":"History's biggest myth"},
{"question":"Einstein failed maths as a child.\nTrue or false?","answer":"FALSE — Einstein excelled at maths from a young age","answer_note":"Einstein mastered calculus by 15. He failed a Swiss school entrance exam in French, not maths, which may have started the myth.","hook":"School legend"},
{"question":"Humans evolved from chimpanzees.\nTrue or false?","answer":"FALSE — humans and chimps share a common ancestor","answer_note":"Humans didn't evolve from chimps. Both species share a common ancestor that lived about 6–7 million years ago.","hook":"Evolution truth"},
{"question":"The forbidden fruit in the Garden of Eden was an apple.\nTrue or false?","answer":"FALSE — the Bible never specifies the fruit","answer_note":"The Book of Genesis says 'fruit of the tree' but never specifies apple. The apple association came from Latin translations and art.","hook":"Biblical detail"},
{"question":"Bulls are enraged by the colour red.\nTrue or false?","answer":"FALSE — bulls are colour-blind to red","answer_note":"Bulls can't distinguish red from green. It's the motion of the matador's cape that agitates them, not the colour.","hook":"Bullfighting myth"},
{"question":"We only use 10% of our brain.\nTrue or false?","answer":"FALSE — we use virtually all of our brain","answer_note":"Brain scans show activity in nearly all regions. Different areas activate for different tasks. The 10% myth is completely unfounded.","hook":"Brain myth"},
{"question":"Goldfish have a 3-second memory.\nTrue or false?","answer":"FALSE — goldfish can remember things for months","answer_note":"Studies show goldfish can remember training and routines for months. The 3-second memory is a complete myth.","hook":"Pet myth"},
{"question":"Lightning never strikes the same place twice.\nTrue or false?","answer":"FALSE — lightning strikes the same place repeatedly","answer_note":"The Empire State Building is struck by lightning about 100 times per year. Tall objects attract lightning repeatedly.","hook":"Weather myth"},
{"question":"Hair and fingernails continue to grow after death.\nTrue or false?","answer":"FALSE — the skin retracts, creating the illusion of growth","answer_note":"Hair and nails need glucose to grow, which stops at death. The skin dehydrates and contracts, making them appear longer.","hook":"Creepy myth"},
{"question":"Swallowed chewing gum takes 7 years to digest.\nTrue or false?","answer":"FALSE — gum passes through the digestive system normally","answer_note":"While the gum base isn't digested, it moves through your system within days just like other indigestible material.","hook":"Playground myth"},
{"question":"Mount Everest is the world's tallest mountain.\nTrue or false?","answer":"TRUE — by elevation above sea level, Everest is tallest (8,849m)","answer_note":"Everest is tallest measured from sea level. Mauna Kea in Hawaii is tallest measured from its base on the ocean floor.","hook":"Depends how you measure"},
{"question":"Ostriches bury their heads in the sand when scared.\nTrue or false?","answer":"FALSE — ostriches never bury their heads in sand","answer_note":"Ostriches dig holes in the ground to tend their eggs and may lower their heads near the ground — never bury them.","hook":"Animal myth"},
{"question":"You should wait 30 minutes after eating before swimming.\nTrue or false?","answer":"FALSE — no scientific evidence supports this rule","answer_note":"There's no evidence that swimming after eating is dangerous. Mild discomfort is possible, but no documented cramping deaths.","hook":"Swimming rule"},
{"question":"Vaccines cause autism.\nTrue or false?","answer":"FALSE — thoroughly debunked by hundreds of studies","answer_note":"The original 1998 study claiming a link was fraudulent and retracted. Dozens of large-scale studies confirm vaccines do not cause autism.","hook":"Medical myth"},
{"question":"Bats are completely blind.\nTrue or false?","answer":"FALSE — bats can see, and many have good vision","answer_note":"All bat species can see. Megabats (fruit bats) have large eyes and good vision. Echolocation supplements but doesn't replace sight.","hook":"Bat myth"},
{"question":"Humans have five senses.\nTrue or false?","answer":"FALSE — humans have at least 10+ senses","answer_note":"In addition to the classic 5, humans also sense balance, temperature, pain, proprioception (body position), and hunger, among others.","hook":"Senses myth"},
{"question":"The Great Wall of China is the longest wall ever built.\nTrue or false?","answer":"TRUE — at over 21,000 km total","answer_note":"All sections of the Great Wall combined stretch over 21,000 km. It is indeed the longest structure ever built by humans.","hook":"True this time"},
{"question":"Walt Disney's body was cryogenically frozen after his death.\nTrue or false?","answer":"FALSE — Disney was cremated two days after his death","answer_note":"Walt Disney died in December 1966 and was cremated. The cryonics story is a persistent urban legend with no factual basis.","hook":"Hollywood legend"},
{"question":"Elephants are afraid of mice.\nTrue or false?","answer":"FALSE — elephants typically ignore mice","answer_note":"Studies and observations show elephants don't react fearfully to mice. They may be startled by sudden movements of any small animal, but aren't specifically afraid of mice.","hook":"Cartoon vs reality"},
{"question":"The colour orange is named after the fruit.\nTrue or false?","answer":"TRUE — the fruit came first, then the colour name","answer_note":"Before the 16th century, English speakers called the colour 'yellow-red' or 'geoluhread'. Once oranges arrived in Europe, the colour took the fruit's name.","hook":"Word origin"},
{"question":"Frankenstein is the name of the monster.\nTrue or false?","answer":"FALSE — Frankenstein is the name of the scientist","answer_note":"In Mary Shelley's 1818 novel, Victor Frankenstein is the scientist. His creation is never given a name — often called 'the creature'.","hook":"Classic novel"},
{"question":"The Eiffel Tower is taller in summer.\nTrue or false?","answer":"TRUE — it expands by up to 15 cm in the heat","answer_note":"Metal expands when heated. The Eiffel Tower (iron) can be up to 15 cm taller on a hot summer day than in winter.","hook":"Physics fact"},
{"question":"Carrots improve your night vision.\nTrue or false?","answer":"FALSE — this was a WWII propaganda myth","answer_note":"The British spread this rumour to conceal their use of radar technology. While vitamin A supports eye health, carrots won't give you night vision.","hook":"WWII myth"},
{"question":"Seasons are caused by Earth's distance from the Sun.\nTrue or false?","answer":"FALSE — seasons are caused by Earth's tilt","answer_note":"Earth's axis is tilted 23.5°. When the northern hemisphere tilts toward the Sun, it's summer — not because we're closer to it.","hook":"Season myth"},
{"question":"Columbus proved the Earth was round.\nTrue or false?","answer":"FALSE — educated people already knew Earth was round","answer_note":"Ancient Greeks calculated Earth's circumference. Columbus thought he'd found a shorter route to Asia, not that he was proving the shape.","hook":"History myth"},
{"question":"Camels store water in their humps.\nTrue or false?","answer":"FALSE — camel humps store fat, not water","answer_note":"Camel humps are made of fat, which can be converted to water and energy. Camels get most of their water from metabolising this fat.","hook":"Camel myth"},
{"question":"Humans and dinosaurs lived at the same time.\nTrue or false?","answer":"FALSE — 66 million years separate us","answer_note":"Non-avian dinosaurs went extinct about 66 million years ago. Modern humans emerged around 300,000 years ago. Birds are living dinosaurs.","hook":"Timeline myth"},
{"question":"Your blood is blue inside your body.\nTrue or false?","answer":"FALSE — blood is always red, just lighter or darker","answer_note":"Deoxygenated blood is dark red, not blue. Veins appear blue under skin because of how light penetrates tissue.","hook":"Biology myth"},
{"question":"Sugar makes children hyperactive.\nTrue or false?","answer":"FALSE — multiple double-blind studies found no link","answer_note":"Controlled studies show sugar does not cause hyperactivity. The effect parents observe is likely due to the excitement of parties and events where sugary food is served.","hook":"Parent myth"},
{"question":"The tongue map shows different taste zones.\nTrue or false?","answer":"FALSE — the tongue map is a debunked myth from 1901","answer_note":"The 'tongue map' was based on a mistranslation of a German paper. All taste receptor cells appear across the entire tongue.","hook":"Science myth"},
{"question":"Hair grows back thicker after shaving.\nTrue or false?","answer":"FALSE — shaving doesn't affect hair thickness","answer_note":"Shaving cuts hair at the thickest point, making regrowth feel stubbly. But the follicle and thickness are unchanged.","hook":"Shaving myth"},
{"question":"Eating before bed makes you gain more weight.\nTrue or false?","answer":"FALSE — total calories matter, not timing","answer_note":"Weight gain comes from consuming more calories than you burn. Eating at night only causes weight gain if it pushes you into a caloric surplus.","hook":"Diet myth"},
{"question":"The tongue is the strongest muscle in the body.\nTrue or false?","answer":"FALSE — the masseter (jaw muscle) generates the most force","answer_note":"The tongue is highly flexible but the masseter (jaw muscle) generates more biting force. The heart works hardest overall.","hook":"Muscle myth"},
{"question":"Alcohol kills brain cells.\nTrue or false?","answer":"FALSE — alcohol damages connections, not the cells themselves","answer_note":"Moderate drinking doesn't kill neurons but can damage dendrites (connections between cells). Severe alcoholism can cause neuron death.","hook":"Drinking myth"},
{"question":"We have five senses: sight, hearing, touch, taste, smell.\nTrue or false?","answer":"FALSE — we have many more, including proprioception and balance","answer_note":"Humans sense temperature, pain, balance, body position (proprioception), time, and more. The 'five senses' concept dates to Aristotle.","hook":"How many senses?"},
{"question":"Frankenstein was written by Bram Stoker.\nTrue or false?","answer":"FALSE — it was written by Mary Shelley (1818)","answer_note":"Frankenstein was written by Mary Shelley and published in 1818. Bram Stoker wrote Dracula in 1897.","hook":"Author mix-up"},
{"question":"Sherlock Holmes says 'Elementary, my dear Watson' in the books.\nTrue or false?","answer":"FALSE — Arthur Conan Doyle never wrote that line","answer_note":"The exact phrase 'Elementary, my dear Watson' never appears in any Conan Doyle story. It originates from film and stage adaptations.","hook":"Literary myth"},
{"question":"Marco Polo brought pasta from China to Italy.\nTrue or false?","answer":"FALSE — pasta likely existed in Italy before Marco Polo's return","answer_note":"Records of pasta in Italy predate Marco Polo's journey. The story is a persistent myth with no historical evidence.","hook":"Food origin myth"},
{"question":"George Washington had wooden teeth.\nTrue or false?","answer":"FALSE — his dentures were made of ivory, bone, and human teeth","answer_note":"Washington's dentures were made from ivory (elephant and walrus), animal bones, and human teeth. No wood was used.","hook":"Presidential myth"},
{"question":"The Titanic's band played 'Nearer My God to Thee' as it sank.\nTrue or false?","answer":"UNCERTAIN — this is disputed; it may have been 'Songe d'Automne'","answer_note":"Survivor accounts conflict. Some recall a hymn, others recall 'Songe d'Automne'. The exact song is genuinely uncertain.","hook":"Titanic truth"},
{"question":"Great Wall of China is one continuous wall.\nTrue or false?","answer":"FALSE — it's many separate walls built over centuries","answer_note":"The 'Great Wall' is actually multiple walls built by different dynasties over 2,000 years. They're not all connected.","hook":"One wall or many?"},
{"question":"Black holes suck everything in like a vacuum.\nTrue or false?","answer":"FALSE — black holes only attract nearby matter by gravity","answer_note":"If the Sun became a black hole, Earth would continue orbiting normally. Black holes pull in nearby matter but aren't cosmic vacuum cleaners.","hook":"Space myth"},
{"question":"The word 'Ye' in 'Ye Olde' was pronounced 'yee'.\nTrue or false?","answer":"FALSE — 'Ye' was pronounced 'the'","answer_note":"'Y' in old English manuscripts was used to represent the letter thorn (þ), which made the 'th' sound. So 'Ye' = 'The'.","hook":"Language myth"},
{"question":"A coin dropped from the Empire State Building could kill someone.\nTrue or false?","answer":"FALSE — coins reach terminal velocity and wouldn't be lethal","answer_note":"A falling penny reaches terminal velocity of ~100 km/h due to air resistance. It would sting but not kill. It's too small and light.","hook":"Physics myth"},
{"question":"The full name of Los Angeles is 'El Pueblo de Nuestra Señora la Reina de los Ángeles'.\nTrue or false?","answer":"TRUE — though the exact wording varies by historical source","answer_note":"The original 1781 Spanish settlement had a very long name roughly translating to 'The Town of Our Lady the Queen of Angels'.","hook":"Long city name"},
{"question":"Frankenstein was the first science fiction novel.\nTrue or false?","answer":"Debated — it's among the first; possibly THE first","answer_note":"Mary Shelley's Frankenstein (1818) is widely considered the first science fiction novel, though some argue earlier works qualify.","hook":"Genre origins"},
{"question":"The Eiffel Tower was intended to be a temporary structure.\nTrue or false?","answer":"TRUE — it was meant to be dismantled after 20 years","answer_note":"The Eiffel Tower was built for the 1889 World's Fair and scheduled for demolition in 1909. Its usefulness as a radio tower saved it.","hook":"Nearly demolished"},
{"question":"Humans and Neanderthals never interbred.\nTrue or false?","answer":"FALSE — modern humans carry Neanderthal DNA","answer_note":"DNA analysis confirms that modern humans (outside sub-Saharan Africa) carry 1–4% Neanderthal DNA from interbreeding about 50,000 years ago.","hook":"DNA evidence"},
{"question":"The shortest US president was James Madison at 5'4\".\nTrue or false?","answer":"TRUE — Madison is recorded as the shortest US president","answer_note":"James Madison stood about 5'4\" (163 cm), making him the shortest US president. He was also among the lightest at about 100 lbs.","hook":"Presidential trivia"},
{"question":"King Tut's tomb had a curse that killed those who opened it.\nTrue or false?","answer":"FALSE — the 'curse' is a myth; most expedition members lived long lives","answer_note":"Howard Carter, who opened the tomb in 1922, lived another 17 years. Most expedition members lived to old age. The 'curse' was media invention.","hook":"Mummy's curse"},
]

# Fix the Finland/Norway item
for item in new_items:
    if "Finland and Norway" in item["question"]:
        item["question"] = "Australia is in the southern hemisphere, which means their seasons are reversed from the UK.\nTrue or false?"
        item["answer"] = "TRUE — Australian summer is in December"
        item["answer_note"] = "Because Australia is south of the equator, their summer runs December–February and winter runs June–August — opposite to the northern hemisphere."
        item["hook"] = "Upside-down seasons"

for i, item in enumerate(new_items):
    item["id"] = f"me_{next_n + i:04d}"

result = existing + new_items
json.dump(result, open(F, "w", encoding="utf-8"), indent=2, ensure_ascii=False)
print(f"me: {len(existing)} -> {len(result)} items (+{len(new_items)})")
