import json
from pathlib import Path

F = Path("C:/Users/prawn/OneDrive/Documents/djamies1.github.io/trueorfalse/statements.json")
existing = json.load(open(F, encoding="utf-8"))
ids = [int(x["id"].split("_")[-1]) for x in existing if x.get("id", "").startswith("tof_")]
next_n = max(ids, default=0) + 1

new_items = [
    # ANIMALS - TRUE
    {"statement": "Sharks are the only fish that can blink with both eyes.", "verdict": "FALSE", "explanation": "Sharks don't actually have eyelids in the traditional sense. Some species have a nictitating membrane but can't 'blink' both eyes.", "category": "animals", "hook": "Think you know sharks?"},
    {"statement": "A group of crows is called a murder.", "verdict": "TRUE", "explanation": "A gathering of crows is indeed called a murder of crows, a collective noun dating back centuries.", "category": "animals", "hook": "Creepy collective nouns!"},
    {"statement": "Elephants are the only animals that cannot jump.", "verdict": "FALSE", "explanation": "Hippos and sloths also cannot jump. Elephants are notable but not the only ones.", "category": "animals", "hook": "Who else can't jump?"},
    {"statement": "Butterflies taste with their feet.", "verdict": "TRUE", "explanation": "Butterflies have taste sensors on their feet, allowing them to taste what they land on.", "category": "animals", "hook": "Feet first tasting!"},
    {"statement": "A cow can walk upstairs but not downstairs.", "verdict": "TRUE", "explanation": "The structure of a cow's knees makes it easy to go up stairs but very difficult to go down.", "category": "animals", "hook": "One way traffic!"},
    {"statement": "Penguins mate for life.", "verdict": "FALSE", "explanation": "Most penguin species are socially monogamous within a season, but many switch partners between breeding seasons.", "category": "animals", "hook": "Not so romantic!"},
    {"statement": "A snail can sleep for 3 years.", "verdict": "TRUE", "explanation": "Snails can hibernate or estivate (summer sleep) for up to 3 years when conditions are too dry.", "category": "animals", "hook": "Ultimate power nap!"},
    {"statement": "Goldfish have a memory span of only 3 seconds.", "verdict": "FALSE", "explanation": "Goldfish actually have a memory of several months. The 3-second myth has been debunked by researchers.", "category": "animals", "hook": "Goldfish are smarter than you think!"},
    {"statement": "Dolphins sleep with one eye open.", "verdict": "TRUE", "explanation": "Dolphins practice unihemispheric sleep — one half of their brain rests while the other stays alert.", "category": "animals", "hook": "Always on watch!"},
    {"statement": "Flamingos are born pink.", "verdict": "FALSE", "explanation": "Flamingo chicks are born white or gray. They turn pink from carotenoid pigments in the algae and shrimp they eat.", "category": "animals", "hook": "You are what you eat!"},
    {"statement": "A group of owls is called a parliament.", "verdict": "TRUE", "explanation": "Owls gathered together are collectively known as a parliament, reflecting their wise reputation.", "category": "animals", "hook": "Wise legislators!"},
    {"statement": "Sea otters hold hands while sleeping.", "verdict": "TRUE", "explanation": "Sea otters hold hands (or wrap in kelp) while sleeping to avoid drifting apart from their group.", "category": "animals", "hook": "Adorably true!"},
    {"statement": "All polar bears are left-handed.", "verdict": "FALSE", "explanation": "This is a popular myth. No scientific evidence supports that polar bears are predominantly left-pawed.", "category": "animals", "hook": "Myth busted!"},
    {"statement": "Octopuses have three hearts.", "verdict": "TRUE", "explanation": "Octopuses have three hearts: two branchial hearts pump blood through the gills, one systemic heart pumps it through the body.", "category": "animals", "hook": "Triple heart power!"},
    {"statement": "Cats always land on their feet.", "verdict": "FALSE", "explanation": "Cats have a righting reflex but don't always land safely — especially from very short falls before the reflex activates.", "category": "animals", "hook": "Don't test this at home!"},
    # SCIENCE
    {"statement": "Lightning never strikes the same place twice.", "verdict": "FALSE", "explanation": "Lightning absolutely can and does strike the same place multiple times. The Empire State Building is struck about 23 times per year.", "category": "science", "hook": "Common myth busted!"},
    {"statement": "Humans share 50% of their DNA with bananas.", "verdict": "TRUE", "explanation": "Humans and bananas share about 50% of their DNA because many basic genetic functions are the same across all life.", "category": "science", "hook": "We're part banana!"},
    {"statement": "Hot water freezes faster than cold water.", "verdict": "TRUE", "explanation": "This is called the Mpemba effect. Under certain conditions hot water can freeze faster than cold water, though scientists still debate the exact cause.", "category": "science", "hook": "Counterintuitive physics!"},
    {"statement": "Diamonds are made from coal.", "verdict": "FALSE", "explanation": "Most diamonds formed deep in Earth's mantle from pure carbon under extreme pressure, long before coal-forming plants existed.", "category": "science", "hook": "Different origins!"},
    {"statement": "The Great Wall of China is visible from space.", "verdict": "FALSE", "explanation": "The wall is too narrow to be seen from space with the naked eye. Many astronauts have confirmed this.", "category": "science", "hook": "Space myth!"},
    {"statement": "Humans have more than 5 senses.", "verdict": "TRUE", "explanation": "Beyond the 5 classic senses, humans also have proprioception, thermoception, balance (equilibrioception), and others.", "category": "science", "hook": "More than meets the eye!"},
    {"statement": "The sun is a yellow star.", "verdict": "FALSE", "explanation": "The Sun is actually classified as a white star. It appears yellow due to Earth's atmosphere scattering shorter wavelengths.", "category": "science", "hook": "Our sun is white!"},
    {"statement": "Water expands when it freezes.", "verdict": "TRUE", "explanation": "Water is unusual in that it expands about 9% in volume when it freezes, making ice less dense than liquid water.", "category": "science", "hook": "Why ice floats!"},
    {"statement": "The human body replaces all its cells every 7 years.", "verdict": "FALSE", "explanation": "Different cells replace at different rates — some neurons in the brain last a lifetime, red blood cells last 4 months.", "category": "science", "hook": "Not quite!"},
    {"statement": "Pluto is no longer classified as a planet.", "verdict": "TRUE", "explanation": "In 2006, the IAU redefined 'planet' and reclassified Pluto as a dwarf planet.", "category": "science", "hook": "Poor Pluto!"},
    {"statement": "Humans and dinosaurs coexisted.", "verdict": "FALSE", "explanation": "Non-avian dinosaurs went extinct about 66 million years ago. Modern humans appeared only about 300,000 years ago.", "category": "science", "hook": "65 million years apart!"},
    # HISTORY
    {"statement": "Napoleon Bonaparte was short for his time.", "verdict": "FALSE", "explanation": "Napoleon was about 5'7\" (170 cm), average height for a Frenchman of his era. The 'short' story is largely a British propaganda myth.", "category": "history", "hook": "History's biggest myth!"},
    {"statement": "Vikings wore horned helmets.", "verdict": "FALSE", "explanation": "The horned helmet is a 19th-century romantic invention. Actual Viking helmets were plain iron or leather.", "category": "history", "hook": "Hollywood invented this!"},
    {"statement": "Abraham Lincoln was the tallest US President.", "verdict": "TRUE", "explanation": "Abraham Lincoln stood 6'4\" (193 cm), making him the tallest US President in history.", "category": "history", "hook": "Tall in more ways than one!"},
    {"statement": "The Great Fire of London destroyed St. Paul's Cathedral.", "verdict": "TRUE", "explanation": "The 1666 fire destroyed the old St. Paul's Cathedral. It was subsequently rebuilt by Christopher Wren.", "category": "history", "hook": "Rising from the ashes!"},
    {"statement": "Cleopatra was Egyptian.", "verdict": "FALSE", "explanation": "Cleopatra was Greek Macedonian, a descendant of Ptolemy I who served under Alexander the Great. She was the first Ptolemaic ruler to learn Egyptian.", "category": "history", "hook": "Not Egyptian!"},
    {"statement": "The Eiffel Tower was originally meant to be temporary.", "verdict": "TRUE", "explanation": "The Eiffel Tower was built as a temporary exhibit for the 1889 World's Fair and was slated for demolition in 1909 before radio antennas made it useful.", "category": "history", "hook": "Almost torn down!"},
    {"statement": "Ancient Romans used urine as a mouthwash.", "verdict": "TRUE", "explanation": "Romans used urine (which contains ammonia) to whiten teeth and clean clothes. Portuguese urine was considered especially effective.", "category": "history", "hook": "Ancient hygiene was interesting!"},
    {"statement": "The first Olympic Games were held in Rome.", "verdict": "FALSE", "explanation": "The ancient Olympics were held in Olympia, Greece, starting around 776 BC.", "category": "history", "hook": "Greek, not Roman!"},
    {"statement": "Marie Curie was the first woman to win a Nobel Prize.", "verdict": "TRUE", "explanation": "Marie Curie won the Nobel Prize in Physics in 1903, making her the first woman to win a Nobel Prize.", "category": "history", "hook": "A trailblazer!"},
    # GEOGRAPHY
    {"statement": "Australia is the world's largest island.", "verdict": "FALSE", "explanation": "Greenland is the world's largest island. Australia is classified as a continent, not an island.", "category": "geography", "hook": "Continent vs island!"},
    {"statement": "The Amazon River flows into the Atlantic Ocean.", "verdict": "TRUE", "explanation": "The Amazon River empties into the Atlantic Ocean near Marajó Island in Brazil.", "category": "geography", "hook": "River trivia!"},
    {"statement": "Mount Everest is the tallest mountain on Earth measured from sea level.", "verdict": "TRUE", "explanation": "Mount Everest at 8,849m is the tallest from sea level. Mauna Kea is taller from base to peak.", "category": "geography", "hook": "Depends how you measure!"},
    {"statement": "Russia is the largest country in the world.", "verdict": "TRUE", "explanation": "Russia covers about 17.1 million km², making it by far the world's largest country by area.", "category": "geography", "hook": "Enormous country!"},
    {"statement": "The Sahara is the world's largest desert.", "verdict": "FALSE", "explanation": "Antarctica is technically the world's largest desert (cold deserts count). The Sahara is the largest hot desert.", "category": "geography", "hook": "Frozen desert!"},
    {"statement": "Brazil is the only Portuguese-speaking country in South America.", "verdict": "TRUE", "explanation": "Brazil is the only country in South America where Portuguese is the official language, a result of Portuguese colonization.", "category": "geography", "hook": "Unique in South America!"},
    {"statement": "The Dead Sea is the world's deepest lake.", "verdict": "FALSE", "explanation": "Lake Baikal in Siberia is the world's deepest lake at 1,642m. The Dead Sea is the world's lowest body of water.", "category": "geography", "hook": "Lowest, not deepest!"},
    # FOOD & DRINK
    {"statement": "Honey never expires.", "verdict": "TRUE", "explanation": "Honey found in Egyptian tombs thousands of years old was still edible. Its low moisture and acidic pH prevent bacterial growth.", "category": "food", "hook": "Ancient sweetness!"},
    {"statement": "White chocolate is a type of chocolate.", "verdict": "FALSE", "explanation": "White chocolate contains no cocoa solids, only cocoa butter, making it technically not 'chocolate' by most definitions.", "category": "food", "hook": "Chocolate debate!"},
    {"statement": "Peanuts are not actually nuts.", "verdict": "TRUE", "explanation": "Peanuts are legumes (like beans and lentils), not true nuts. True nuts include walnuts, almonds, and chestnuts.", "category": "food", "hook": "Nutty classification!"},
    {"statement": "Eating carrots improves your night vision.", "verdict": "FALSE", "explanation": "Carrots have vitamin A which supports eye health, but won't give you enhanced night vision. The myth was WWII British propaganda.", "category": "food", "hook": "WWII myth!"},
    {"statement": "Tomatoes are technically a fruit.", "verdict": "TRUE", "explanation": "Botanically, a tomato is a fruit as it develops from the flower and contains seeds. Culinarily, it's used as a vegetable.", "category": "food", "hook": "Botanically a fruit!"},
    {"statement": "Coffee beans are actually beans.", "verdict": "FALSE", "explanation": "Coffee 'beans' are actually seeds from the coffee plant's cherry-like fruit. They're called beans because of their resemblance to legume beans.", "category": "food", "hook": "Seeds, not beans!"},
    {"statement": "The original Coca-Cola recipe contained cocaine.", "verdict": "TRUE", "explanation": "Early Coca-Cola (1886) contained small amounts of cocaine from coca leaf extract. It was removed around 1903.", "category": "food", "hook": "Original formula!"},
    {"statement": "Bananas are berries but strawberries are not.", "verdict": "TRUE", "explanation": "Botanically, bananas are berries (develop from single flowers with one ovary). Strawberries are accessory fruits, not true berries.", "category": "food", "hook": "Berry confused!"},
    # HUMAN BODY
    {"statement": "We only use 10% of our brains.", "verdict": "FALSE", "explanation": "Brain scans show activity throughout the entire brain. Different regions are active at different times but the '10% myth' is fiction.", "category": "body", "hook": "Famous myth busted!"},
    {"statement": "Fingernails keep growing after death.", "verdict": "FALSE", "explanation": "This is an illusion — dehydration after death causes skin to retract, making nails appear longer.", "category": "body", "hook": "Gruesome myth!"},
    {"statement": "Your tongue has a unique print like your fingerprints.", "verdict": "TRUE", "explanation": "The tongue's texture, shape, and pattern are unique to each individual, similar to fingerprints.", "category": "body", "hook": "Tongue ID!"},
    {"statement": "Humans are the only animals with fingerprints.", "verdict": "FALSE", "explanation": "Koalas and chimpanzees also have fingerprints. Koala prints are nearly indistinguishable from human ones.", "category": "body", "hook": "Koalas could commit crimes!"},
    {"statement": "The brain feels no pain.", "verdict": "TRUE", "explanation": "The brain itself has no pain receptors. Headaches occur in surrounding tissues, blood vessels, and muscles.", "category": "body", "hook": "Painless organ!"},
    {"statement": "You lose most of your body heat through your head.", "verdict": "FALSE", "explanation": "You lose heat proportionally through any uncovered body part. The head isn't special unless it's the only thing exposed.", "category": "body", "hook": "Hat myth!"},
    # TECHNOLOGY & POP CULTURE
    {"statement": "The first computer bug was an actual insect.", "verdict": "TRUE", "explanation": "In 1947, a real moth was found trapped in Harvard's Mark II computer. Grace Hopper's team taped it into their log, coining 'debugging'.", "category": "technology", "hook": "A literal bug!"},
    {"statement": "Nintendo was founded in the 1800s.", "verdict": "TRUE", "explanation": "Nintendo was founded in 1889 by Fusajiro Yamauchi in Kyoto, Japan, originally making playing cards.", "category": "technology", "hook": "Ancient gaming company!"},
    {"statement": "The first email was sent in 1971.", "verdict": "TRUE", "explanation": "Ray Tomlinson sent the first email in 1971, also choosing the @ symbol to separate user names from host computers.", "category": "technology", "hook": "@ the beginning!"},
    {"statement": "The QWERTY keyboard layout was designed to slow down typists.", "verdict": "FALSE", "explanation": "QWERTY was designed to reduce jamming on mechanical typewriters by separating commonly paired letters, not to slow typists.", "category": "technology", "hook": "Layout myth!"},
    {"statement": "The average person spends more time on their phone than sleeping.", "verdict": "FALSE", "explanation": "The average person sleeps about 7 hours vs phone use of 3–4 hours. But the gap is narrowing!", "category": "technology", "hook": "Screen time!"},
    # RANDOM
    {"statement": "You can't hum while holding your nose.", "verdict": "TRUE", "explanation": "Humming requires air to pass through your nose. Blocking it stops the sound. Try it right now!", "category": "random", "hook": "Try it yourself!"},
    {"statement": "A day on Venus is longer than a year on Venus.", "verdict": "TRUE", "explanation": "Venus rotates so slowly that one day (243 Earth days) is longer than its orbital year (225 Earth days).", "category": "random", "hook": "Time is weird in space!"},
    {"statement": "It is impossible to sneeze with your eyes open.", "verdict": "TRUE", "explanation": "The sneeze reflex automatically closes the eyes. Trying to keep them open during a sneeze is extremely difficult.", "category": "random", "hook": "Blink reflex!"},
    {"statement": "The world's oldest known tree is over 5,000 years old.", "verdict": "TRUE", "explanation": "Methuselah, a Great Basin bristlecone pine in California, is estimated to be about 5,000 years old.", "category": "random", "hook": "Ancient tree!"},
    {"statement": "Laughter is unique to humans.", "verdict": "FALSE", "explanation": "Rats, chimps, and dogs all show laugh-like behaviors during play, including specific vocalizations.", "category": "random", "hook": "Animals laugh too!"},
    {"statement": "Bubble wrap was originally invented as wallpaper.", "verdict": "TRUE", "explanation": "Alfred Fielding and Marc Chavannes invented bubble wrap in 1957 as textured wallpaper. It failed as wallpaper but succeeded as packaging.", "category": "random", "hook": "Popping wallpaper!"},
    {"statement": "The dot over the letter i has a name.", "verdict": "TRUE", "explanation": "The dot over a lowercase 'i' is called a tittle. The same term applies to the dot over 'j'.", "category": "random", "hook": "It's called a tittle!"},
    {"statement": "Scissors were invented before paper.", "verdict": "TRUE", "explanation": "Early scissors date back to ancient Egypt around 1500 BC. Paper was invented in China around 100 AD.", "category": "random", "hook": "Scissors first!"},
    {"statement": "The Hawaiian alphabet has only 13 letters.", "verdict": "TRUE", "explanation": "The Hawaiian alphabet has 13 letters: 5 vowels (A, E, I, O, U) and 8 consonants (H, K, L, M, N, P, W, and the ʻokina).", "category": "random", "hook": "Short alphabet!"},
    {"statement": "Coca-Cola was originally green.", "verdict": "FALSE", "explanation": "Coca-Cola was never green. The bottle originally used greenish glass which may have contributed to this myth.", "category": "random", "hook": "Bottle confusion!"},
    {"statement": "The plastic tips on shoelaces are called aglets.", "verdict": "TRUE", "explanation": "Aglets are the small plastic or metal tips at the ends of shoelaces that prevent fraying.", "category": "random", "hook": "Now you know!"},
    {"statement": "It takes 7 years to digest swallowed gum.", "verdict": "FALSE", "explanation": "While gum base isn't fully digested, it passes through your system in a few days just like other indigestible foods.", "category": "random", "hook": "Gum myth!"},
    {"statement": "Cleopatra lived closer in time to the Moon landing than to the construction of the Great Pyramid.", "verdict": "TRUE", "explanation": "The Great Pyramid was built around 2560 BC. Cleopatra lived around 69–30 BC. The Moon landing was 1969. Cleopatra is closer to 1969 than to 2560 BC.", "category": "random", "hook": "Mind-bending timeline!"},
    {"statement": "The shortest war in history lasted 38 minutes.", "verdict": "TRUE", "explanation": "The Anglo-Zanzibar War of 1896 lasted between 38 and 45 minutes, the shortest recorded war in history.", "category": "random", "hook": "Quick war!"},
    {"statement": "Honey bees can recognize human faces.", "verdict": "TRUE", "explanation": "Research shows honey bees can recognize human facial features using the same techniques they use to distinguish flowers.", "category": "random", "hook": "Bees know your face!"},
    {"statement": "There are more trees on Earth than stars in the Milky Way.", "verdict": "TRUE", "explanation": "Earth has approximately 3 trillion trees. The Milky Way has an estimated 100–400 billion stars.", "category": "random", "hook": "Trees beat stars!"},
    {"statement": "Mount Everest is the world's tallest mountain measured from Earth's core.", "verdict": "FALSE", "explanation": "Mount Chimborazo in Ecuador is the farthest point from Earth's center due to the planet's equatorial bulge.", "category": "random", "hook": "Depends how you measure!"},
    {"statement": "Sharks are older than trees.", "verdict": "TRUE", "explanation": "Sharks have existed for about 450 million years. Trees only evolved about 350 million years ago.", "category": "random", "hook": "Ancient predator!"},
    {"statement": "You can die from drinking too much water.", "verdict": "TRUE", "explanation": "Water intoxication (hyponatremia) occurs when excessive water dilutes sodium levels in the blood, which can be fatal.", "category": "random", "hook": "Too much of anything!"},
    {"statement": "The inventor of the frisbee was turned into a frisbee after his death.", "verdict": "TRUE", "explanation": "Walter Morrison's ashes were incorporated into memorial frisbees after he died in 2010, per his own request.", "category": "random", "hook": "Unusual legacy!"},
    {"statement": "Oxford University is older than the Aztec Empire.", "verdict": "TRUE", "explanation": "Oxford University was founded around 1096–1167. The Aztec Empire was established around 1428.", "category": "random", "hook": "Ancient institution!"},
    {"statement": "Sound travels faster than light.", "verdict": "FALSE", "explanation": "Light travels at 299,792 km/s while sound travels at only 343 m/s in air. Light is about 880,000 times faster.", "category": "random", "hook": "Light wins easily!"},
]

for i, item in enumerate(new_items):
    item["id"] = f"tof_{next_n + i:04d}"

result = existing + new_items
json.dump(result, open(F, "w", encoding="utf-8"), indent=2, ensure_ascii=False)
print(f"trueorfalse: {len(existing)} -> {len(result)} items (+{len(new_items)})")
