import json
from pathlib import Path

F = Path("C:/Users/prawn/OneDrive/Documents/djamies1.github.io/emojiquiz/questions.json")
existing = json.load(open(F, encoding="utf-8"))
ids = [int(x["id"].split("_")[-1]) for x in existing if x.get("id", "").startswith("eq_")]
next_n = max(ids, default=0) + 1

new_items = [
    # --- MOVIES ---
    {"emojis": "🦁👑🌍", "answer": "The Lion King", "category": "movies", "hook": "Hakuna Matata!"},
    {"emojis": "🕷️🕸️👦", "answer": "Spider-Man", "category": "movies", "hook": "Your friendly neighborhood hero!"},
    {"emojis": "🧊❄️👸", "answer": "Frozen", "category": "movies", "hook": "Let it go!"},
    {"emojis": "🧙‍♂️💍🌋", "answer": "Lord of the Rings", "category": "movies", "hook": "One ring to rule them all!"},
    {"emojis": "🤖🚗🔊", "answer": "Transformers", "category": "movies", "hook": "More than meets the eye!"},
    {"emojis": "🐟🔵🌊", "answer": "Finding Nemo", "category": "movies", "hook": "Just keep swimming!"},
    {"emojis": "🧸🤠⭐", "answer": "Toy Story", "category": "movies", "hook": "To infinity and beyond!"},
    {"emojis": "🦈🏖️😱", "answer": "Jaws", "category": "movies", "hook": "You're gonna need a bigger boat!"},
    {"emojis": "👻🚫🚷", "answer": "Ghostbusters", "category": "movies", "hook": "Who ya gonna call?"},
    {"emojis": "🌀⬇️🐰", "answer": "Alice in Wonderland", "category": "movies", "hook": "Down the rabbit hole!"},
    {"emojis": "🦊🐰🏙️", "answer": "Zootopia", "category": "movies", "hook": "Anyone can be anything!"},
    {"emojis": "🚂💨❄️🎄", "answer": "The Polar Express", "category": "movies", "hook": "Believe in the magic!"},
    {"emojis": "🦸‍♀️🌩️⚡", "answer": "Wonder Woman", "category": "movies", "hook": "Amazonian warrior princess!"},
    {"emojis": "🔱🌊🐙", "answer": "Aquaman", "category": "movies", "hook": "King of the seas!"},
    {"emojis": "🎭🃏😈", "answer": "Joker", "category": "movies", "hook": "Why so serious?"},
    {"emojis": "🌌🚀💫🛸", "answer": "Interstellar", "category": "movies", "hook": "Space, time, and love!"},
    {"emojis": "🪖🏝️🦖", "answer": "Kong: Skull Island", "category": "movies", "hook": "Not the Kong you know!"},
    {"emojis": "🎩🐰✨🎪", "answer": "The Prestige", "category": "movies", "hook": "Every great magic trick has three parts!"},
    {"emojis": "🌹👹📚", "answer": "Beauty and the Beast", "category": "movies", "hook": "Tale as old as time!"},
    {"emojis": "🐉🛡️🏰", "answer": "How to Train Your Dragon", "category": "movies", "hook": "Boys and their dragons!"},
    {"emojis": "🎬🕺🎵", "answer": "La La Land", "category": "movies", "hook": "City of stars!"},
    {"emojis": "🧬🦕🏝️", "answer": "Jurassic Park", "category": "movies", "hook": "Life finds a way!"},
    {"emojis": "🕶️💊🐇", "answer": "The Matrix", "category": "movies", "hook": "Red pill or blue pill?"},
    {"emojis": "🏎️💨🔥", "answer": "Fast & Furious", "category": "movies", "hook": "Family and fast cars!"},
    {"emojis": "🌊🚢❄️💔", "answer": "Titanic", "category": "movies", "hook": "I'm the king of the world!"},
    # --- PHRASES ---
    {"emojis": "🌧️👨‍👩‍👧‍👦🤝", "answer": "When it rains it pours", "category": "phrases", "hook": "Bad luck loves company!"},
    {"emojis": "🐦⏰🐛", "answer": "The early bird catches the worm", "category": "phrases", "hook": "Rise and shine!"},
    {"emojis": "🐟🌊🦈", "answer": "Big fish in a small pond", "category": "phrases", "hook": "Being the best in a small group!"},
    {"emojis": "🍰🍽️😋", "answer": "Have your cake and eat it too", "category": "phrases", "hook": "You can't have everything!"},
    {"emojis": "💧🪨💧", "answer": "Water off a duck's back", "category": "phrases", "hook": "Let it roll right off you!"},
    {"emojis": "🐎🚪🔒", "answer": "Closing the stable door after the horse bolted", "category": "phrases", "hook": "Too little, too late!"},
    {"emojis": "🌩️⚡🍾", "answer": "Lightning in a bottle", "category": "phrases", "hook": "Capturing something magical!"},
    {"emojis": "👀🏠🔎", "answer": "The elephant in the room", "category": "phrases", "hook": "The obvious problem nobody mentions!"},
    {"emojis": "🥄🌕🍲", "answer": "Born with a silver spoon", "category": "phrases", "hook": "Growing up privileged!"},
    {"emojis": "🐝🪣🍯", "answer": "You catch more flies with honey", "category": "phrases", "hook": "Kindness works better than force!"},
    {"emojis": "🐍🌿🌱", "answer": "Snake in the grass", "category": "phrases", "hook": "A hidden traitor!"},
    {"emojis": "🎯🎪🎭", "answer": "Hit the nail on the head", "category": "phrases", "hook": "Exactly right!"},
    {"emojis": "🌙⭐🔮", "answer": "Shoot for the moon", "category": "phrases", "hook": "Aim high!"},
    {"emojis": "🐘🧠💪", "answer": "An elephant never forgets", "category": "phrases", "hook": "Perfect memory!"},
    {"emojis": "🪙💰💵", "answer": "A penny saved is a penny earned", "category": "phrases", "hook": "Be frugal!"},
    # --- SONGS ---
    {"emojis": "🎸🤘🔥😈", "answer": "Highway to Hell", "category": "songs", "hook": "AC/DC classic rock anthem!"},
    {"emojis": "💃🌴🌊🏝️", "answer": "Kokomo", "category": "songs", "hook": "Beach Boys paradise!"},
    {"emojis": "👑🎶🎤", "answer": "Queen", "category": "songs", "hook": "We will rock you!"},
    {"emojis": "🌞🌛⭐🎵", "answer": "Here Comes the Sun", "category": "songs", "hook": "Beatles classic!"},
    {"emojis": "💜🟣🌂🎵", "answer": "Purple Rain", "category": "songs", "hook": "Prince's masterpiece!"},
    {"emojis": "🤖🎵🕺", "answer": "Mr. Roboto", "category": "songs", "hook": "Styx's robot anthem!"},
    {"emojis": "🚂🎵🌍", "answer": "Life is a Highway", "category": "songs", "hook": "Tom Cochrane road trip!"},
    {"emojis": "❤️🔥💥💔", "answer": "Burning Love", "category": "songs", "hook": "Elvis's fiery love song!"},
    {"emojis": "🌈🦄✨🎤", "answer": "True Colors", "category": "songs", "hook": "Cyndi Lauper's anthem!"},
    {"emojis": "🕺🪩✨🌃", "answer": "Stayin Alive", "category": "songs", "hook": "Bee Gees disco classic!"},
    {"emojis": "🌊🏄‍♂️☀️🎸", "answer": "Surfin USA", "category": "songs", "hook": "Beach Boys summer hit!"},
    {"emojis": "🪄🎩💫🎵", "answer": "Magic", "category": "songs", "hook": "You do something to me!"},
    {"emojis": "🌙🎵🎸🎶", "answer": "Fly Me to the Moon", "category": "songs", "hook": "Frank Sinatra classic!"},
    {"emojis": "🍋🐝🎤💛", "answer": "Lemonade", "category": "songs", "hook": "Beyoncé's album!"},
    {"emojis": "⚡🎸🔊🎵", "answer": "Thunderstruck", "category": "songs", "hook": "AC/DC electrifying opener!"},
    # --- GEOGRAPHY ---
    {"emojis": "🗼🥐🍷🇫🇷", "answer": "France", "category": "geography", "hook": "Ooh la la!"},
    {"emojis": "🍕🏛️⛲🇮🇹", "answer": "Italy", "category": "geography", "hook": "The boot of Europe!"},
    {"emojis": "🍣🗻⛩️🇯🇵", "answer": "Japan", "category": "geography", "hook": "Land of the Rising Sun!"},
    {"emojis": "🦘🐨🏄‍♂️🇦🇺", "answer": "Australia", "category": "geography", "hook": "G'day mate!"},
    {"emojis": "🌵🎭🌶️🇲🇽", "answer": "Mexico", "category": "geography", "hook": "Viva Mexico!"},
    {"emojis": "🧉🥩💃🇦🇷", "answer": "Argentina", "category": "geography", "hook": "Tango and steak!"},
    {"emojis": "🐘🌴🏛️🇮🇳", "answer": "India", "category": "geography", "hook": "Land of spices!"},
    {"emojis": "🏔️⌚🧀🇨🇭", "answer": "Switzerland", "category": "geography", "hook": "Neutral and precise!"},
    {"emojis": "🌷🚲💧🇳🇱", "answer": "Netherlands", "category": "geography", "hook": "Land of windmills!"},
    {"emojis": "🐉🏯🍜🇨🇳", "answer": "China", "category": "geography", "hook": "The Middle Kingdom!"},
    {"emojis": "🦁🌍☀️🇿🇦", "answer": "South Africa", "category": "geography", "hook": "Rainbow Nation!"},
    {"emojis": "🎇🕌☪️🇹🇷", "answer": "Turkey", "category": "geography", "hook": "Bridge between East and West!"},
    {"emojis": "🏔️🎿❄️🇨🇦", "answer": "Canada", "category": "geography", "hook": "O Canada!"},
    {"emojis": "🌺🏄‍♀️🌊🇺🇸", "answer": "Hawaii", "category": "geography", "hook": "Aloha state!"},
    {"emojis": "🗽🍎🎭🗼", "answer": "New York", "category": "geography", "hook": "The city that never sleeps!"},
    # --- ANIMALS ---
    {"emojis": "🖤⬜🐾🦴", "answer": "Dalmatian", "category": "animals", "hook": "101 of them!"},
    {"emojis": "🐴⚫⬜", "answer": "Zebra", "category": "animals", "hook": "Nature's barcode!"},
    {"emojis": "🦟🩸🌙", "answer": "Vampire Bat", "category": "animals", "hook": "The only mammal that feeds exclusively on blood!"},
    {"emojis": "🐢🌊❤️", "answer": "Sea Turtle", "category": "animals", "hook": "Ancient ocean traveler!"},
    {"emojis": "🐺❄️🌙", "answer": "Arctic Wolf", "category": "animals", "hook": "Howling at the northern lights!"},
    {"emojis": "🐠🔴⬛", "answer": "Clownfish", "category": "animals", "hook": "Finding it in the reef!"},
    {"emojis": "🦩🩷🦢", "answer": "Flamingo", "category": "animals", "hook": "Pink from what they eat!"},
    {"emojis": "🐊🌿🌊", "answer": "Crocodile", "category": "animals", "hook": "Living dinosaur!"},
    {"emojis": "🦜🌿🗣️", "answer": "Parrot", "category": "animals", "hook": "Polly wants a cracker!"},
    {"emojis": "🦦🐟🤲", "answer": "Sea Otter", "category": "animals", "hook": "They hold hands while sleeping!"},
    {"emojis": "🐌🐚🌿", "answer": "Snail", "category": "animals", "hook": "Carrying home on its back!"},
    {"emojis": "🕷️🕸️🔴⚫", "answer": "Black Widow Spider", "category": "animals", "hook": "Don't mess with her!"},
    {"emojis": "🐘🚿💧", "answer": "Elephant", "category": "animals", "hook": "Natural garden hose!"},
    {"emojis": "🦅🌄🏔️", "answer": "Bald Eagle", "category": "animals", "hook": "Symbol of America!"},
    {"emojis": "🐙🎨🌊", "answer": "Octopus", "category": "animals", "hook": "Master of disguise!"},
    # --- FOOD ---
    {"emojis": "🍅🧄🌿🍝", "answer": "Spaghetti Bolognese", "category": "food", "hook": "Classic Italian comfort food!"},
    {"emojis": "🥑🍋🧂🫙", "answer": "Guacamole", "category": "food", "hook": "Avocado's finest form!"},
    {"emojis": "🍞🧅🥩🥗", "answer": "Burger", "category": "food", "hook": "American classic!"},
    {"emojis": "🍫🥛🎂", "answer": "Chocolate Cake", "category": "food", "hook": "Dessert perfection!"},
    {"emojis": "🥜🍓🍞", "answer": "Peanut Butter and Jelly", "category": "food", "hook": "American lunchbox staple!"},
    {"emojis": "🍋🍯🫖", "answer": "Lemon Honey Tea", "category": "food", "hook": "Soothing remedy!"},
    {"emojis": "🌮🌽🌶️🥑", "answer": "Tacos", "category": "food", "hook": "Taco Tuesday!"},
    {"emojis": "🍕🧀🍅🫕", "answer": "Margherita Pizza", "category": "food", "hook": "The original pizza!"},
    {"emojis": "🍜🥚🐷🌿", "answer": "Ramen", "category": "food", "hook": "Japanese noodle heaven!"},
    {"emojis": "🫔🌯🥗🌶️", "answer": "Burrito", "category": "food", "hook": "Rolled and stuffed!"},
    {"emojis": "🍤🥢🌊", "answer": "Sushi", "category": "food", "hook": "Japanese delicacy!"},
    {"emojis": "🍟🧂🥔", "answer": "French Fries", "category": "food", "hook": "Crispy potato perfection!"},
    {"emojis": "🫐🍦🎉", "answer": "Blueberry Ice Cream", "category": "food", "hook": "Cool and fruity!"},
    {"emojis": "🥞🍁🧈", "answer": "Pancakes with Maple Syrup", "category": "food", "hook": "Weekend breakfast classic!"},
    {"emojis": "🍩☕📰", "answer": "Donuts and Coffee", "category": "food", "hook": "Classic morning combo!"},
    # --- SPORTS ---
    {"emojis": "⚽🥅🏆", "answer": "Football (Soccer)", "category": "sports", "hook": "The beautiful game!"},
    {"emojis": "🏀🏀🏆🦁", "answer": "Basketball", "category": "sports", "hook": "Nothing but net!"},
    {"emojis": "🎾🏅🌿", "answer": "Tennis", "category": "sports", "hook": "Love means zero!"},
    {"emojis": "🏊‍♂️🌊🥇", "answer": "Swimming", "category": "sports", "hook": "Gliding through water!"},
    {"emojis": "🥊🥋👊", "answer": "Boxing", "category": "sports", "hook": "Float like a butterfly!"},
    {"emojis": "⛷️❄️🏔️", "answer": "Skiing", "category": "sports", "hook": "Downhill rush!"},
    {"emojis": "🏈🦅📺", "answer": "American Football", "category": "sports", "hook": "Super Bowl Sunday!"},
    {"emojis": "⚾🧢🌭", "answer": "Baseball", "category": "sports", "hook": "America's pastime!"},
    {"emojis": "🏇🐎🏆", "answer": "Horse Racing", "category": "sports", "hook": "Sport of kings!"},
    {"emojis": "🚴‍♂️🏔️🇫🇷", "answer": "Tour de France", "category": "sports", "hook": "Ultimate cycling challenge!"},
    {"emojis": "🤸‍♀️🎀🏅", "answer": "Gymnastics", "category": "sports", "hook": "Grace and power combined!"},
    {"emojis": "🏹🎯🌲", "answer": "Archery", "category": "sports", "hook": "Aim true!"},
    {"emojis": "🛹🔥🎮", "answer": "Skateboarding", "category": "sports", "hook": "Tricks and flips!"},
    {"emojis": "🏐🏖️☀️", "answer": "Beach Volleyball", "category": "sports", "hook": "Sand between your toes!"},
    {"emojis": "🥌🧹❄️🎯", "answer": "Curling", "category": "sports", "hook": "Chess on ice!"},
    # --- BOOKS ---
    {"emojis": "🧙‍♂️⚡🏫🦉", "answer": "Harry Potter", "category": "books", "hook": "The boy who lived!"},
    {"emojis": "💍🌋🧝‍♂️⚔️", "answer": "The Lord of the Rings", "category": "books", "hook": "One ring to rule them all!"},
    {"emojis": "🦁🧥❄️🚪", "answer": "The Lion the Witch and the Wardrobe", "category": "books", "hook": "C.S. Lewis's Narnia!"},
    {"emojis": "🐋💧🚢", "answer": "Moby Dick", "category": "books", "hook": "Call me Ishmael!"},
    {"emojis": "🌹🌑💀💘", "answer": "Romeo and Juliet", "category": "books", "hook": "Star-crossed lovers!"},
    {"emojis": "🏝️🐚🔥🧒", "answer": "Lord of the Flies", "category": "books", "hook": "Boys without rules!"},
    {"emojis": "🖤🐷🐴🌾", "answer": "Animal Farm", "category": "books", "hook": "All animals are equal!"},
    {"emojis": "🌙🐢✈️🌹", "answer": "The Little Prince", "category": "books", "hook": "What is essential is invisible!"},
    {"emojis": "💉🧪🔬😱", "answer": "Frankenstein", "category": "books", "hook": "The original monster story!"},
    {"emojis": "🕵️‍♂️🔍🎩💡", "answer": "Sherlock Holmes", "category": "books", "hook": "Elementary, my dear Watson!"},
    {"emojis": "⏰🔙🦎⚙️", "answer": "The Time Machine", "category": "books", "hook": "H.G. Wells's invention!"},
    {"emojis": "🐭🌾👬🐕", "answer": "Of Mice and Men", "category": "books", "hook": "Tell me about the rabbits!"},
    {"emojis": "🌪️👠🐶🌈", "answer": "The Wizard of Oz", "category": "books", "hook": "There's no place like home!"},
    {"emojis": "🎪🐘🐭🎩", "answer": "Dumbo", "category": "books", "hook": "The flying elephant!"},
    {"emojis": "🧭🗺️🏴‍☠️💎", "answer": "Treasure Island", "category": "books", "hook": "X marks the spot!"},
    # --- TV SHOWS ---
    {"emojis": "☂️🎹👨‍👩‍👦‍👦🔍", "answer": "The Umbrella Academy", "category": "tv", "hook": "Dysfunctional superhero family!"},
    {"emojis": "🍕👫📺😂", "answer": "Friends", "category": "tv", "hook": "How you doin?"},
    {"emojis": "⚗️🧪💊💀", "answer": "Breaking Bad", "category": "tv", "hook": "I am the one who knocks!"},
    {"emojis": "👸🔥🐉⚔️", "answer": "Game of Thrones", "category": "tv", "hook": "Winter is coming!"},
    {"emojis": "🌲🏡🔴🔦", "answer": "Stranger Things", "category": "tv", "hook": "The Upside Down!"},
    {"emojis": "🕵️‍♀️💻🌐🔒", "answer": "Mr Robot", "category": "tv", "hook": "Hello friend!"},
    {"emojis": "🏥❤️💔😷", "answer": "Grey's Anatomy", "category": "tv", "hook": "It's a beautiful day to save lives!"},
    {"emojis": "🦸‍♂️⚡💛🏙️", "answer": "The Flash", "category": "tv", "hook": "Fastest man alive!"},
    {"emojis": "🤠🌵⚖️🏜️", "answer": "Breaking Bad", "category": "tv", "hook": "Better Call Saul spinoff's origin!"},
    {"emojis": "🧟‍♂️🌍🔫🏕️", "answer": "The Walking Dead", "category": "tv", "hook": "Survive the apocalypse!"},
    {"emojis": "🚀👨‍🚀🌌🛸", "answer": "The Mandalorian", "category": "tv", "hook": "This is the way!"},
    {"emojis": "🍩☕🏘️👮", "answer": "The Simpsons", "category": "tv", "hook": "D'oh!"},
    {"emojis": "🎒🐱🌍✈️", "answer": "Dora the Explorer", "category": "tv", "hook": "Backpack backpack!"},
    {"emojis": "🟡⚫🎵🎸", "answer": "The Simpsons", "category": "tv", "hook": "Springfield's finest family!"},
    {"emojis": "🧊❄️🥋🏙️", "answer": "Avatar The Last Airbender", "category": "tv", "hook": "Fire Water Earth Air!"},
]

for i, item in enumerate(new_items):
    item["id"] = f"eq_{next_n + i:04d}"

result = existing + new_items
json.dump(result, open(F, "w", encoding="utf-8"), indent=2, ensure_ascii=False)
print(f"emojiquiz: {len(existing)} -> {len(result)} items (+{len(new_items)})")
