import json
from pathlib import Path

F = Path("C:/Users/prawn/OneDrive/Documents/djamies1.github.io/mathchallenge/problems.json")
existing = json.load(open(F, encoding="utf-8"))
ids = [int(x["id"].split("_")[-1]) for x in existing if x.get("id","").startswith("math_")]
next_n = max(ids, default=0) + 1

new_items = [
# ── Order of Operations ────────────────────────────────────────────────────
{"question":"5 + 5 × 5 = ?","answer":"30","answer_note":"Multiply first: 5×5=25, then add 5. Not 50.","category":"order_of_operations","difficulty":"easy","hook":"99% say 50"},
{"question":"2 + 3 × 4 = ?","answer":"14","answer_note":"3×4=12 first, then 2+12=14. Not 20.","category":"order_of_operations","difficulty":"easy","hook":"Most people say 20"},
{"question":"10 - 2 + 3 = ?","answer":"11","answer_note":"Left to right: 10-2=8, then 8+3=11. Not 5.","category":"order_of_operations","difficulty":"easy","hook":"Don't go left to right?"},
{"question":"8 ÷ 4 × 2 = ?","answer":"4","answer_note":"Left to right: 8÷4=2, then 2×2=4. Not 1.","category":"order_of_operations","difficulty":"easy","hook":"Left to right matters!"},
{"question":"3 + 4 × 2 - 1 = ?","answer":"10","answer_note":"4×2=8 first, then 3+8-1=10.","category":"order_of_operations","difficulty":"medium","hook":"What do you get?"},
{"question":"12 ÷ 4 × 3 = ?","answer":"9","answer_note":"Left to right: 12÷4=3, then 3×3=9. Not 1.","category":"order_of_operations","difficulty":"medium","hook":"Most say 1"},
{"question":"4 + 4 ÷ 4 + 4 = ?","answer":"9","answer_note":"Division first: 4÷4=1, then 4+1+4=9. Not 3.","category":"order_of_operations","difficulty":"medium","hook":"Trickier than it looks"},
{"question":"1 + 1 × 1 - 1 ÷ 1 = ?","answer":"1","answer_note":"Multiply/divide first: 1×1=1, 1÷1=1. Then 1+1-1=1.","category":"order_of_operations","difficulty":"easy","hook":"Looks simple…"},
{"question":"3 + 3 × 3 - 3 ÷ 3 = ?","answer":"11","answer_note":"3×3=9, 3÷3=1, then 3+9-1=11.","category":"order_of_operations","difficulty":"medium","hook":"Smarter than you think"},
{"question":"6 + 6 × 6 - 6 ÷ 6 = ?","answer":"41","answer_note":"6×6=36, 6÷6=1, then 6+36-1=41.","category":"order_of_operations","difficulty":"medium","hook":"What's your answer?"},
{"question":"2 × 3² = ?","answer":"18","answer_note":"Exponent first: 3²=9, then 2×9=18. Not 36.","category":"order_of_operations","difficulty":"medium","hook":"Don't square the 2!"},
{"question":"(2+3)² × 2 = ?","answer":"50","answer_note":"Brackets first: (5)²=25, then 25×2=50.","category":"order_of_operations","difficulty":"medium","hook":"Work from the inside out"},
{"question":"√16 + √9 = ?","answer":"7","answer_note":"√16=4, √9=3, then 4+3=7. Not √25=5.","category":"order_of_operations","difficulty":"medium","hook":"Common mistake!"},
{"question":"0.5 × 0.5 = ?","answer":"0.25","answer_note":"Half of a half is a quarter. Not 0.5 or 0.1.","category":"order_of_operations","difficulty":"easy","hook":"What's half of a half?"},
{"question":"1 ÷ 0.5 = ?","answer":"2","answer_note":"Dividing by 0.5 is the same as multiplying by 2.","category":"order_of_operations","difficulty":"easy","hook":"Division surprise!"},
{"question":"50 - 10 × 2 = ?","answer":"30","answer_note":"Multiply first: 10×2=20, then 50-20=30. Not 80.","category":"order_of_operations","difficulty":"easy","hook":"Most say 80"},
{"question":"100 ÷ 5 × 2 = ?","answer":"40","answer_note":"Left to right: 100÷5=20, then 20×2=40. Not 10.","category":"order_of_operations","difficulty":"easy","hook":"Which way first?"},
{"question":"(5-3)² + 4 × 3 = ?","answer":"16","answer_note":"(2)²=4, 4×3=12, then 4+12=16.","category":"order_of_operations","difficulty":"medium","hook":"Step by step"},
{"question":"2³ - 2² = ?","answer":"4","answer_note":"2³=8, 2²=4, then 8-4=4.","category":"order_of_operations","difficulty":"easy","hook":"Power challenge"},
{"question":"5 × 4 ÷ 2 × 3 = ?","answer":"30","answer_note":"Left to right: 20÷2=10, then 10×3=30. Not 3.33.","category":"order_of_operations","difficulty":"medium","hook":"Don't jump ahead"},
{"question":"2 + 4 × (3 - 1) = ?","answer":"10","answer_note":"Brackets: (2)=2, then 4×2=8, then 2+8=10.","category":"order_of_operations","difficulty":"easy","hook":"Brackets beat everything"},
{"question":"10 × 10 ÷ 10 + 10 = ?","answer":"20","answer_note":"Left to right: 100÷10=10, then 10+10=20. Not 100.","category":"order_of_operations","difficulty":"medium","hook":"Do you see the trick?"},
{"question":"3 × (4 + 2) - 2 × 5 = ?","answer":"8","answer_note":"3×6=18, 2×5=10, then 18-10=8.","category":"order_of_operations","difficulty":"medium","hook":"Two brackets, one answer"},
{"question":"8 - (2 × 3) + 4 = ?","answer":"6","answer_note":"2×3=6, then 8-6+4=6.","category":"order_of_operations","difficulty":"easy","hook":"Follow the rules"},
{"question":"10 + 10 × 0 + 10 = ?","answer":"20","answer_note":"10×0=0, then 10+0+10=20. Not 0.","category":"order_of_operations","difficulty":"easy","hook":"Multiplication by zero"},
{"question":"3 × 7 - 4 × 5 = ?","answer":"1","answer_note":"3×7=21, 4×5=20, then 21-20=1.","category":"order_of_operations","difficulty":"medium","hook":"Super close!"},
{"question":"6 × 6 ÷ 6 × 6 = ?","answer":"36","answer_note":"Left to right: 36÷6=6, then 6×6=36.","category":"order_of_operations","difficulty":"medium","hook":"What do you get?"},
{"question":"1000 + 40 + 1000 + 30 + 1000 + 20 + 1000 + 10 = ?","answer":"4100","answer_note":"Add the thousands: 4000. Add the rest: 100. Total: 4100. Not 5000.","category":"order_of_operations","difficulty":"medium","hook":"Viral math trick"},
{"question":"6 × 7 + 3 × 8 = ?","answer":"66","answer_note":"6×7=42, 3×8=24, then 42+24=66.","category":"order_of_operations","difficulty":"medium","hook":"Two multiplications"},
{"question":"9 × 9 - 8 × 8 = ?","answer":"17","answer_note":"9²=81, 8²=64, then 81-64=17.","category":"order_of_operations","difficulty":"easy","hook":"Difference of squares"},
{"question":"15% of 60 = ?","answer":"9","answer_note":"0.15 × 60 = 9. Or: 10%=6, 5%=3, total=9.","category":"order_of_operations","difficulty":"easy","hook":"Mental math check"},
{"question":"20% of 150 = ?","answer":"30","answer_note":"20% = 1/5. 150÷5=30.","category":"order_of_operations","difficulty":"easy","hook":"Quick percentage"},
{"question":"25% of 80 = ?","answer":"20","answer_note":"25% = 1/4. 80÷4=20.","category":"order_of_operations","difficulty":"easy","hook":"Quarter of a number"},
{"question":"100 - 99 + 98 - 97 + 96 - 95 = ?","answer":"3","answer_note":"Each pair (100-99), (98-97), (96-95) equals 1. Three pairs = 3.","category":"order_of_operations","difficulty":"hard","hook":"Pattern recognition"},
{"question":"5! ÷ 4! = ?","answer":"5","answer_note":"5!=120, 4!=24. 120÷24=5. Or simply: 5!/4! = 5.","category":"order_of_operations","difficulty":"hard","hook":"Factorial challenge"},
{"question":"2 × (3 + 4) - 2 × 3 = ?","answer":"8","answer_note":"2×7=14, 2×3=6, then 14-6=8.","category":"order_of_operations","difficulty":"medium","hook":"Two operations"},
{"question":"40% of 75 = ?","answer":"30","answer_note":"40% of 75: 0.4×75=30. Or 75×2÷5=30.","category":"order_of_operations","difficulty":"medium","hook":"Can you do it fast?"},
{"question":"3 × 4 + 8 ÷ 2 = ?","answer":"16","answer_note":"3×4=12, 8÷2=4, then 12+4=16.","category":"order_of_operations","difficulty":"easy","hook":"Two rules at once"},
{"question":"(3 + 4) × (8 - 3) = ?","answer":"35","answer_note":"(7)×(5)=35.","category":"order_of_operations","difficulty":"easy","hook":"Brackets first"},
{"question":"50 ÷ (2 + 3) × 4 = ?","answer":"40","answer_note":"50÷5=10, then 10×4=40.","category":"order_of_operations","difficulty":"medium","hook":"Don't skip the brackets"},
# ── Sequences ─────────────────────────────────────────────────────────────
{"question":"1, 4, 9, 16, 25, ___ = ?","answer":"36","answer_note":"Perfect squares: 1²,2²,3²,4²,5²,6²=36.","category":"sequence","difficulty":"easy","hook":"What comes next?"},
{"question":"1, 1, 2, 3, 5, 8, 13, ___ = ?","answer":"21","answer_note":"Fibonacci: each term is the sum of the two before it. 8+13=21.","category":"sequence","difficulty":"easy","hook":"Famous sequence"},
{"question":"2, 3, 5, 7, 11, 13, ___ = ?","answer":"17","answer_note":"Prime numbers. 17 is the next prime after 13.","category":"sequence","difficulty":"easy","hook":"What's the pattern?"},
{"question":"1, 3, 6, 10, 15, ___ = ?","answer":"21","answer_note":"Triangular numbers: add 2, then 3, then 4… add 6 to 15=21.","category":"sequence","difficulty":"medium","hook":"Triangle challenge"},
{"question":"1, 8, 27, 64, 125, ___ = ?","answer":"216","answer_note":"Perfect cubes: 1³,2³,3³,4³,5³,6³=216.","category":"sequence","difficulty":"medium","hook":"Cube numbers"},
{"question":"2, 4, 8, 16, 32, ___ = ?","answer":"64","answer_note":"Powers of 2: each term doubles. 32×2=64.","category":"sequence","difficulty":"easy","hook":"Doubling sequence"},
{"question":"1, 2, 4, 7, 11, 16, ___ = ?","answer":"22","answer_note":"Differences increase by 1: +1,+2,+3,+4,+5,+6. 16+6=22.","category":"sequence","difficulty":"hard","hook":"Increasing gaps"},
{"question":"3, 6, 12, 24, 48, ___ = ?","answer":"96","answer_note":"Each term doubles. 48×2=96.","category":"sequence","difficulty":"easy","hook":"Double each time"},
{"question":"1, 3, 9, 27, 81, ___ = ?","answer":"243","answer_note":"Powers of 3: multiply by 3 each time. 81×3=243.","category":"sequence","difficulty":"easy","hook":"Powers of 3"},
{"question":"0, 1, 3, 6, 10, ___ = ?","answer":"15","answer_note":"Triangular numbers: add 1,2,3,4,5. 10+5=15.","category":"sequence","difficulty":"medium","hook":"Triangle numbers"},
{"question":"1, 2, 6, 24, 120, ___ = ?","answer":"720","answer_note":"Factorials: 1!,2!,3!,4!,5!,6!=720.","category":"sequence","difficulty":"hard","hook":"Can you spot it?"},
{"question":"2, 5, 11, 23, 47, ___ = ?","answer":"95","answer_note":"Each term: multiply by 2 and add 1. 47×2+1=95.","category":"sequence","difficulty":"hard","hook":"Hidden formula"},
{"question":"16, 8, 4, 2, 1, ___ = ?","answer":"0.5","answer_note":"Each term halves. 1÷2=0.5.","category":"sequence","difficulty":"easy","hook":"Getting smaller"},
{"question":"3, 1, 4, 1, 5, 9, 2, 6, ___ = ?","answer":"5","answer_note":"Digits of pi: 3.14159265... The next digit is 5.","category":"sequence","difficulty":"hard","hook":"Famous constant"},
{"question":"31, 28, 31, 30, 31, 30, ___ = ?","answer":"31","answer_note":"Days in each month Jan–Jul. July has 31 days.","category":"sequence","difficulty":"medium","hook":"Spot the theme"},
{"question":"5, 6, 5, 4, 5, 6, 5, ___ = ?","answer":"4","answer_note":"Repeating pattern: 5,6,5,4. The next is 4.","category":"sequence","difficulty":"medium","hook":"Repeating pattern"},
{"question":"7, 10, 8, 11, 9, 12, ___ = ?","answer":"10","answer_note":"Alternating +3 then -2. 12-2=10.","category":"sequence","difficulty":"medium","hook":"Two-step pattern"},
{"question":"2, 6, 12, 20, 30, ___ = ?","answer":"42","answer_note":"n×(n+1): 1×2,2×3,3×4,4×5,5×6,6×7=42.","category":"sequence","difficulty":"hard","hook":"Oblong numbers"},
{"question":"1, 3, 7, 15, 31, ___ = ?","answer":"63","answer_note":"Each term: double and add 1. 31×2+1=63.","category":"sequence","difficulty":"hard","hook":"Double plus one"},
{"question":"100, 91, 83, 76, 70, ___ = ?","answer":"65","answer_note":"Differences: -9,-8,-7,-6,-5. 70-5=65.","category":"sequence","difficulty":"hard","hook":"Shrinking gaps"},
{"question":"1, 4, 13, 40, 121, ___ = ?","answer":"364","answer_note":"Each term: multiply by 3 and add 1. 121×3+1=364.","category":"sequence","difficulty":"hard","hook":"Triple plus one"},
{"question":"1, 2, 3, 5, 8, 13, 21, ___ = ?","answer":"34","answer_note":"Fibonacci: 13+21=34.","category":"sequence","difficulty":"easy","hook":"Add the last two"},
{"question":"0, 3, 8, 15, 24, ___ = ?","answer":"35","answer_note":"n²-1: 1-1=0,4-1=3,9-1=8,16-1=15,25-1=24,36-1=35.","category":"sequence","difficulty":"hard","hook":"Square minus one"},
{"question":"10, 9, 7, 4, 0, ___ = ?","answer":"-5","answer_note":"Differences: -1,-2,-3,-4,-5. 0-5=-5.","category":"sequence","difficulty":"medium","hook":"Going negative"},
{"question":"1, 10, 100, 1000, ___ = ?","answer":"10000","answer_note":"Powers of 10: 10⁰,10¹,10²,10³,10⁴=10000.","category":"sequence","difficulty":"easy","hook":"Powers of ten"},
{"question":"2, 10, 30, 68, 130, ___ = ?","answer":"222","answer_note":"n³+n: 1+1,8+2,27+3,64+4,125+5,216+6=222.","category":"sequence","difficulty":"hard","hook":"Cube pattern"},
# ── Word / Trick Problems ──────────────────────────────────────────────────
{"question":"A bat and ball cost $1.10. The bat costs $1 more. How much is the ball?","answer":"$0.05","answer_note":"If ball=x, bat=x+1: 2x+1=1.10, so x=0.05. Not $0.10!","category":"trick_question","difficulty":"hard","hook":"Harvard gets this wrong"},
{"question":"You're in a race. You pass the person in 2nd. What place are you in?","answer":"2nd place","answer_note":"You took their spot. You didn't pass 1st place. You're now 2nd.","category":"trick_question","difficulty":"easy","hook":"Trick question!"},
{"question":"How many months have 28 days?","answer":"All 12 months","answer_note":"Every month has at least 28 days. All 12 qualify.","category":"trick_question","difficulty":"easy","hook":"Everyone gets this wrong"},
{"question":"A farmer has 17 sheep. All but 9 die. How many are left?","answer":"9","answer_note":"'All but 9' means 9 survive. The rest is just flavour text.","category":"trick_question","difficulty":"easy","hook":"Read it carefully"},
{"question":"You have 10 oranges. You take 3. How many do YOU have?","answer":"3","answer_note":"You took 3 — you HAVE 3. The bowl has 7.","category":"trick_question","difficulty":"easy","hook":"Who has what?"},
{"question":"What's half of 2 + 2?","answer":"3","answer_note":"Half of 2 is 1. 1 + 2 = 3. Not 2.","category":"trick_question","difficulty":"easy","hook":"Read it again"},
{"question":"How many birthdays does the average person have?","answer":"1","answer_note":"You only have one birthday — the day you were born. You celebrate it many times.","category":"trick_question","difficulty":"easy","hook":"Easy, right?"},
{"question":"I have 2 coins totalling 30 cents. One is NOT a nickel. What are they?","answer":"A quarter and a nickel","answer_note":"The ONE that's not a nickel is the quarter. The other coin CAN be a nickel.","category":"trick_question","difficulty":"medium","hook":"Read the clue"},
{"question":"A doctor gives 3 pills, one every 30 minutes. How long until all are taken?","answer":"1 hour","answer_note":"Pill 1 at 0:00, pill 2 at 0:30, pill 3 at 1:00. Only 60 minutes total.","category":"trick_question","difficulty":"easy","hook":"Count carefully"},
{"question":"What weighs more: a pound of feathers or a pound of gold?","answer":"They weigh the same","answer_note":"Both weigh exactly one pound. Weight is weight.","category":"trick_question","difficulty":"easy","hook":"Classic trick"},
{"question":"How many 3-cent stamps are in a dozen?","answer":"12","answer_note":"A dozen is always 12, regardless of the value of the stamp.","category":"trick_question","difficulty":"easy","hook":"Dozen = ?"},
{"question":"If 5 cats catch 5 mice in 5 minutes, how long for 1 cat to catch 1 mouse?","answer":"5 minutes","answer_note":"Each cat catches 1 mouse in 5 minutes. Same rate.","category":"trick_question","difficulty":"medium","hook":"Rate question"},
{"question":"Divide 30 by half and add 10. What's the answer?","answer":"70","answer_note":"30 ÷ 0.5 = 60 (dividing by half doubles it). 60 + 10 = 70. Not 25.","category":"trick_question","difficulty":"hard","hook":"Divide by HALF"},
{"question":"What next: 8, 5, 4, 9, 1, 7, 6, 3, 2, ___?","answer":"0","answer_note":"Numbers in alphabetical order: Eight, Five, Four, Nine, One, Seven, Six, Three, Two, Zero.","category":"trick_question","difficulty":"hard","hook":"Not a math pattern!"},
{"question":"How many animals of each kind did Moses take on the ark?","answer":"None — that was Noah","answer_note":"Moses parted the Red Sea. Noah built the ark. Common mix-up!","category":"trick_question","difficulty":"medium","hook":"Bible trick"},
{"question":"A plane crashes on the US/Canada border. Where are survivors buried?","answer":"You don't bury survivors","answer_note":"Survivors are alive — they don't need burial. The word 'survivors' is the key.","category":"trick_question","difficulty":"easy","hook":"Read every word"},
{"question":"What is the max times you can subtract 10 from 100?","answer":"Once","answer_note":"After the first subtraction, you have 90, not 100. So only once from 100.","category":"trick_question","difficulty":"easy","hook":"Maximum times?"},
{"question":"If it takes 5 machines 5 min to make 5 widgets, how long for 100 machines to make 100 widgets?","answer":"5 minutes","answer_note":"Each machine makes 1 widget in 5 minutes — scale doesn't change the rate.","category":"trick_question","difficulty":"medium","hook":"Scale thinking"},
{"question":"A snail in a 20-ft well climbs 5 ft daily and slides 4 at night. Days to escape?","answer":"16 days","answer_note":"Net gain 1ft/day. After 15 days: 15 ft. On day 16: climbs 5 ft to reach 20, escapes.","category":"word_problem","difficulty":"hard","hook":"Classic puzzle"},
{"question":"Two fathers and two sons go fishing, catch 3 fish and each gets 1. How?","answer":"3 people: grandfather, father, son","answer_note":"The father is both a father AND a son. Only 3 people total.","category":"trick_question","difficulty":"medium","hook":"Who's there?"},
{"question":"What's the sum of all numbers from 1 to 100?","answer":"5050","answer_note":"Gauss's formula: 100×101÷2=5050. Pair 1+100, 2+99, etc. — 50 pairs of 101.","category":"word_problem","difficulty":"medium","hook":"Gauss solved this at age 8"},
{"question":"In a family: each son has equal brothers and sisters. Each daughter has twice as many brothers as sisters. How many of each?","answer":"4 sons, 3 daughters","answer_note":"s-1=d and s=2(d-1). Solving: d=3, s=4.","category":"logic","difficulty":"hard","hook":"Family puzzle"},
{"question":"How many squares are on a standard 8×8 chessboard?","answer":"204","answer_note":"Count all sizes: 64+49+36+25+16+9+4+1=204. Not just 64.","category":"logic","difficulty":"hard","hook":"Not 64!"},
{"question":"How many handshakes if 5 people each shake hands with everyone once?","answer":"10","answer_note":"5×4÷2=10. Each of 5 people shakes 4 hands, but each shake is shared.","category":"logic","difficulty":"medium","hook":"Handshake puzzle"},
{"question":"A car does 60 miles at 30 mph and 60 miles at 60 mph. Average speed?","answer":"40 mph","answer_note":"Total time: 2h+1h=3h. Total distance: 120 miles. 120÷3=40 mph. Not 45.","category":"logic","difficulty":"hard","hook":"Average speed trick"},
{"question":"How many cuts to slice a log into 10 equal pieces?","answer":"9","answer_note":"Each cut adds one piece. You start with 1, need 10 — so 9 cuts.","category":"logic","difficulty":"easy","hook":"Count the cuts"},
{"question":"What two numbers multiply to 48 and add to 14?","answer":"6 and 8","answer_note":"6×8=48 and 6+8=14. ✓","category":"logic","difficulty":"medium","hook":"Find the pair"},
{"question":"The only number equal to the count of its own letters?","answer":"4","answer_note":"F-O-U-R = 4 letters. No other number in English has this property.","category":"logic","difficulty":"medium","hook":"Self-describing"},
{"question":"You flip a coin 10 times and get 10 heads. Odds of heads on next flip?","answer":"50%","answer_note":"Each flip is independent. Past flips don't affect future ones.","category":"logic","difficulty":"easy","hook":"Gambler's fallacy"},
{"question":"Train A at 60 mph, Train B at 90 mph, 300 miles apart. How long to meet?","answer":"2 hours","answer_note":"They close at 60+90=150 mph. 300÷150=2 hours.","category":"word_problem","difficulty":"medium","hook":"Meeting trains"},
{"question":"A grandfather is twice his son's age. His son is twice his grandson's age. Together they're 140. How old is the grandson?","answer":"20 years old","answer_note":"g+2g+4g=7g=140, g=20.","category":"word_problem","difficulty":"hard","hook":"Three generations"},
{"question":"What is the next prime number after 17?","answer":"19","answer_note":"18 is divisible by 2, 3, 6, 9. 19 is only divisible by 1 and 19.","category":"common_knowledge","difficulty":"easy","hook":"Quick prime check"},
{"question":"How many degrees are in all angles of a triangle?","answer":"180°","answer_note":"All triangles, regardless of shape, have interior angles summing to 180°.","category":"common_knowledge","difficulty":"easy","hook":"Triangle rule"},
{"question":"How many faces does a cube have?","answer":"6","answer_note":"Top, bottom, front, back, left, right — 6 faces.","category":"common_knowledge","difficulty":"easy","hook":"3D shape"},
{"question":"What is 2¹⁰?","answer":"1024","answer_note":"2¹⁰=1024. Important in computing — why computer memory uses 1KB=1024 bytes.","category":"common_knowledge","difficulty":"medium","hook":"Powers of 2"},
{"question":"What is the area of a circle with radius 5? (use π≈3.14)","answer":"78.5","answer_note":"Area = π×r² = 3.14×25 = 78.5","category":"common_knowledge","difficulty":"medium","hook":"Circle area"},
{"question":"What is 12 × 12?","answer":"144","answer_note":"144. Also called a gross. 12 dozens = 144.","category":"common_knowledge","difficulty":"easy","hook":"Times table check"},
{"question":"What is 1/3 as a percentage?","answer":"33.3% (repeating)","answer_note":"1÷3=0.3333... = 33.3̄%. It never ends.","category":"common_knowledge","difficulty":"easy","hook":"Fraction to percent"},
{"question":"How many edges does a cube have?","answer":"12","answer_note":"4 edges on top, 4 on bottom, 4 vertical edges connecting them = 12.","category":"common_knowledge","difficulty":"medium","hook":"Edges vs faces"},
{"question":"In a right triangle with legs 3 and 4, what is the hypotenuse?","answer":"5","answer_note":"3²+4²=9+16=25=5². The famous 3-4-5 Pythagorean triple.","category":"common_knowledge","difficulty":"easy","hook":"Pythagoras!"},
{"question":"What is the value of π to 4 decimal places?","answer":"3.1416","answer_note":"π = 3.14159... rounded to 4 decimal places is 3.1416.","category":"common_knowledge","difficulty":"medium","hook":"Pi trivia"},
{"question":"How many degrees are in a full rotation?","answer":"360°","answer_note":"A full circle is 360 degrees. A half turn is 180°, quarter turn is 90°.","category":"common_knowledge","difficulty":"easy","hook":"Full circle"},
{"question":"What is the square root of 196?","answer":"14","answer_note":"14×14=196. ✓","category":"common_knowledge","difficulty":"medium","hook":"Square root test"},
{"question":"What is 7 × 8?","answer":"56","answer_note":"7×8=56. One of the most commonly miscalculated multiplication facts.","category":"common_knowledge","difficulty":"easy","hook":"Times table"},
{"question":"How many sides does an octagon have?","answer":"8","answer_note":"Octo = 8 in Latin. Stop signs are octagons.","category":"common_knowledge","difficulty":"easy","hook":"Shape check"},
{"question":"What is the perimeter of a square with side 7?","answer":"28","answer_note":"Perimeter = 4×side = 4×7 = 28.","category":"common_knowledge","difficulty":"easy","hook":"Perimeter"},
{"question":"What is the only even prime number?","answer":"2","answer_note":"2 is prime (divisible only by 1 and itself) and the only even one.","category":"common_knowledge","difficulty":"easy","hook":"Prime curiosity"},
]

for i, item in enumerate(new_items):
    item["id"] = f"math_{next_n + i:04d}"

result = existing + new_items
json.dump(result, open(F, "w", encoding="utf-8"), indent=2, ensure_ascii=False)
print(f"math: {len(existing)} -> {len(result)} items (+{len(new_items)})")
