import json
from pathlib import Path

F = Path("C:/Users/prawn/OneDrive/Documents/djamies1.github.io/trueorfalse/statements.json")
existing = json.load(open(F, encoding="utf-8"))
ids = [int(x["id"].split("_")[-1]) for x in existing if x.get("id","").startswith("tof_")]
next_n = max(ids, default=0) + 1

new_items = [
    # ANIMALS
    {"statement": "Cows have four stomachs.", "verdict": "FALSE", "explanation": "Cows have one stomach with four compartments: rumen, reticulum, omasum, and abomasum. Technically one stomach, four chambers.", "category": "animals", "hook": "One stomach, four parts!"},
    {"statement": "A group of lions is called a pride.", "verdict": "TRUE", "explanation": "A group of lions is correctly called a pride. It typically consists of related females, their cubs, and a small number of adult males.", "category": "animals", "hook": "Lion pride!"},
    {"statement": "Dogs sweat through their tongues.", "verdict": "FALSE", "explanation": "Dogs pant to cool down, but they actually sweat through their paw pads — not their tongues.", "category": "animals", "hook": "Paw sweat!"},
    {"statement": "Sharks are mammals.", "verdict": "FALSE", "explanation": "Sharks are fish — they're cartilaginous fish (class Chondrichthyes). Mammals breathe air and nurse young with milk.", "category": "animals", "hook": "Fish not mammals!"},
    {"statement": "Elephants are afraid of mice.", "verdict": "FALSE", "explanation": "This is a popular myth. Studies show elephants pay no special attention to mice. They are startled by sudden movements, though.", "category": "animals", "hook": "Elephant myth!"},
    {"statement": "A cheetah can outrun a horse over long distances.", "verdict": "FALSE", "explanation": "Cheetahs are faster in short bursts (70+ mph), but can only sustain top speed for 20–30 seconds. Horses outpace them over long distances.", "category": "animals", "hook": "Sprint vs endurance!"},
    {"statement": "Wolves mate for life.", "verdict": "TRUE", "explanation": "Wolves typically form monogamous pair bonds that last for life. An alpha pair leads the pack and breeds together.", "category": "animals", "hook": "Loyal wolves!"},
    {"statement": "A rhinoceros horn is made of bone.", "verdict": "FALSE", "explanation": "Rhino horns are made of keratin — the same protein that makes up human fingernails and hair, not bone.", "category": "animals", "hook": "Keratin horn!"},
    {"statement": "Hummingbirds can fly backwards.", "verdict": "TRUE", "explanation": "Hummingbirds are the only birds that can fly backwards, sideways, and even upside down thanks to their unique rotating wing joints.", "category": "animals", "hook": "Reverse flight!"},
    {"statement": "Ostriches bury their heads in the sand when scared.", "verdict": "FALSE", "explanation": "Ostriches don't bury their heads in sand. They lower their heads to the ground to tend to their eggs in nests, which looks like hiding from a distance.", "category": "animals", "hook": "Ancient myth!"},
    {"statement": "A baby kangaroo is smaller than a cherry when born.", "verdict": "TRUE", "explanation": "A newborn kangaroo (joey) is about 2cm long — roughly the size of a grape or jellybean — and must crawl to its mother's pouch.", "category": "animals", "hook": "Tiny joey!"},
    {"statement": "Penguins propose to their mates with pebbles.", "verdict": "TRUE", "explanation": "Male Gentoo penguins search for the perfect pebble to present to potential mates. If accepted, they use it to build their nest together.", "category": "animals", "hook": "Pebble proposal!"},
    {"statement": "Sharks must keep swimming to stay alive.", "verdict": "FALSE", "explanation": "Some shark species, like the nurse shark, can pump water over their gills and rest on the ocean floor. But some open-ocean sharks do need to swim continuously.", "category": "animals", "hook": "Some sharks rest!"},
    {"statement": "Camels store water in their humps.", "verdict": "FALSE", "explanation": "Camel humps store fat, not water. The fat can be metabolized for energy. Camels stay hydrated through their bloodstream and efficient kidneys.", "category": "animals", "hook": "Fat, not water!"},
    {"statement": "A snail can have over 25,000 teeth.", "verdict": "TRUE", "explanation": "Garden snails have a ribbon of thousands of tiny teeth called a radula — some species have over 25,000 teeth for rasping food.", "category": "animals", "hook": "Toothy snail!"},
    # SCIENCE
    {"statement": "Sound travels faster in water than in air.", "verdict": "TRUE", "explanation": "Sound travels about 1,480 m/s in water versus 343 m/s in air — about 4x faster. Denser media generally conduct sound better.", "category": "science", "hook": "Underwater sound!"},
    {"statement": "There are more stars in the universe than grains of sand on Earth's beaches.", "verdict": "TRUE", "explanation": "Estimates suggest 10^24 stars in the observable universe vs about 7.5x10^18 grains of sand — stars win by 100,000x.", "category": "science", "hook": "Stars vs sand!"},
    {"statement": "Glass is a solid.", "verdict": "FALSE (sort of)", "explanation": "Glass is technically an amorphous solid or supercooled liquid — it has a disordered atomic structure. Old windows appear thicker at the bottom from manufacturing, not from flow.", "category": "science", "hook": "Amorphous solid!"},
    {"statement": "Humans share 60% of their DNA with bananas.", "verdict": "FALSE", "explanation": "Humans share about 50% of their DNA with bananas, not 60%. Still astonishing!", "category": "science", "hook": "How much banana?"},
    {"statement": "The human eye can detect a candle flame from 48 km away on a clear night.", "verdict": "TRUE", "explanation": "Under ideal conditions, the human eye can theoretically detect a candle flame at a distance of up to 48 km (30 miles) in darkness.", "category": "science", "hook": "Super sight!"},
    {"statement": "Oxygen is the most abundant element in Earth's crust.", "verdict": "TRUE", "explanation": "Oxygen makes up about 46% of Earth's crust by mass — mostly bound in rocks and minerals like silicates.", "category": "science", "hook": "Oxygen everywhere!"},
    {"statement": "The sun makes a sound.", "verdict": "TRUE", "explanation": "The Sun does produce sound waves from its convective activity, but sound can't travel through the vacuum of space — we can't hear it.", "category": "science", "hook": "Soundless space!"},
    {"statement": "Humans and neanderthals interbred.", "verdict": "TRUE", "explanation": "DNA evidence confirms that Homo sapiens and Neanderthals interbred. Non-African humans carry 1–4% Neanderthal DNA.", "category": "science", "hook": "Ancient interbreeding!"},
    {"statement": "A bolt of lightning is hotter than the surface of the Sun.", "verdict": "TRUE", "explanation": "A lightning bolt can reach 30,000 K (about 5x hotter than the Sun's surface at 5,778 K).", "category": "science", "hook": "Hotter than the Sun!"},
    {"statement": "There is no gravity in space.", "verdict": "FALSE", "explanation": "Gravity exists everywhere in space — it just weakens with distance. Astronauts feel weightless because they're in freefall, not because there's no gravity.", "category": "science", "hook": "Gravity myth!"},
    # HISTORY
    {"statement": "The Great Fire of London happened in 1666.", "verdict": "TRUE", "explanation": "The Great Fire of London began on September 2, 1666, in a bakery on Pudding Lane and burned for three days.", "category": "history", "hook": "London ablaze!"},
    {"statement": "Genghis Khan's empire was larger than the Roman Empire.", "verdict": "TRUE", "explanation": "The Mongol Empire at its peak covered 24 million km². The Roman Empire at its peak was about 5 million km².", "category": "history", "hook": "Mongol vs Roman!"},
    {"statement": "The Eiffel Tower was built for the 1900 World's Fair.", "verdict": "FALSE", "explanation": "The Eiffel Tower was built for the 1889 World's Fair (Exposition Universelle), celebrating the centennial of the French Revolution.", "category": "history", "hook": "1889 not 1900!"},
    {"statement": "The first country to use paper money was China.", "verdict": "TRUE", "explanation": "China began using paper money (jiaozi) during the Tang Dynasty around the 7th century AD — centuries before Europe.", "category": "history", "hook": "Paper money origin!"},
    {"statement": "Cleopatra was a contemporary of Julius Caesar and Mark Antony.", "verdict": "TRUE", "explanation": "Cleopatra had famous relationships with both Julius Caesar and later Mark Antony in the 1st century BC.", "category": "history", "hook": "Ancient alliances!"},
    {"statement": "The Pyramids of Giza were built by slaves.", "verdict": "FALSE", "explanation": "Modern evidence suggests the pyramids were built by paid, skilled workers who received food, medical care, and burial honors near the pyramids.", "category": "history", "hook": "Not slaves!"},
    {"statement": "Beethoven was deaf when he composed his 9th Symphony.", "verdict": "TRUE", "explanation": "Beethoven had become almost completely deaf by the time he composed his 9th Symphony, which premiered in 1824.", "category": "history", "hook": "Deaf composer!"},
    {"statement": "The Cold War involved direct military combat between the USA and USSR.", "verdict": "FALSE", "explanation": "The Cold War was characterized by political tension, proxy wars, and arms race — the US and USSR never directly fought each other militarily.", "category": "history", "hook": "Proxy wars!"},
    # FOOD
    {"statement": "Avocados are technically a berry.", "verdict": "TRUE", "explanation": "Botanically, an avocado is a single-seeded berry. It develops from a single flower with one ovary, meeting the botanical definition of a berry.", "category": "food", "hook": "Berry avocado!"},
    {"statement": "Potatoes are native to Ireland.", "verdict": "FALSE", "explanation": "Potatoes are native to South America (Peru and Bolivia). They were introduced to Europe in the 16th century, later becoming crucial in Ireland.", "category": "food", "hook": "South American origin!"},
    {"statement": "Dark chocolate is healthier than milk chocolate.", "verdict": "TRUE", "explanation": "Dark chocolate has higher cocoa content, more antioxidants (flavonoids), less sugar and milk fat than milk chocolate — generally considered healthier.", "category": "food", "hook": "Dark is better!"},
    {"statement": "Eating before swimming causes dangerous cramps.", "verdict": "FALSE", "explanation": "While vigorous swimming right after a large meal may cause minor discomfort, there is no evidence that eating before swimming causes dangerous cramps.", "category": "food", "hook": "Swimming myth!"},
    {"statement": "The world's most expensive coffee comes from cat poop.", "verdict": "TRUE", "explanation": "Kopi Luwak is coffee made from beans that have been eaten and excreted by Asian palm civets. It can cost up to $600 per pound.", "category": "food", "hook": "Poop coffee!"},
    # GEOGRAPHY
    {"statement": "Antarctica is a desert.", "verdict": "TRUE", "explanation": "Antarctica is the world's largest desert by area, with less than 200mm of precipitation annually in most areas — meeting the desert definition.", "category": "geography", "hook": "Frozen desert!"},
    {"statement": "Spain and Morocco are separated by only 14 km.", "verdict": "TRUE", "explanation": "The Strait of Gibraltar separates Europe (Spain) from Africa (Morocco) at its narrowest point of just 14 km.", "category": "geography", "hook": "Narrow strait!"},
    {"statement": "The Amazon River contains more water than the next 7 largest rivers combined.", "verdict": "TRUE", "explanation": "The Amazon discharges about 20% of all freshwater flowing into Earth's oceans — more than the next 7 rivers combined.", "category": "geography", "hook": "Amazon power!"},
    {"statement": "Mount Kilimanjaro has glaciers at its summit.", "verdict": "TRUE", "explanation": "Kilimanjaro in Tanzania has glaciers near its 5,895m summit, though they are rapidly shrinking due to climate change.", "category": "geography", "hook": "African glacier!"},
    {"statement": "The Nile flows south to north.", "verdict": "TRUE", "explanation": "The Nile flows from south (source in Uganda) to north, emptying into the Mediterranean Sea in Egypt.", "category": "geography", "hook": "North-flowing Nile!"},
    # RANDOM
    {"statement": "You cannot fold a standard piece of paper more than 7 times.", "verdict": "TRUE", "explanation": "Due to thickness doubling with each fold, it becomes physically impossible to fold a standard piece of paper more than 7 times by hand.", "category": "random", "hook": "Try it!"},
    {"statement": "Blue is the rarest color found in nature.", "verdict": "TRUE", "explanation": "True blue pigment is extremely rare in nature. Most animals appearing blue use structural coloring (light scattering) rather than actual blue pigment.", "category": "random", "hook": "Rare blue!"},
    {"statement": "The word 'set' has the most definitions in the English language.", "verdict": "TRUE", "explanation": "According to the Oxford English Dictionary, 'set' has 430 different definitions — more than any other English word.", "category": "random", "hook": "Most meanings!"},
    {"statement": "You can see the color of a star's temperature.", "verdict": "TRUE", "explanation": "Cooler stars appear red or orange; medium stars (like our Sun) appear yellow-white; hotter stars appear blue or blue-white.", "category": "random", "hook": "Star colors!"},
    {"statement": "A day on Earth is exactly 24 hours long.", "verdict": "FALSE", "explanation": "A day on Earth is actually 23 hours, 56 minutes, and 4 seconds (a sidereal day). The 24-hour solar day accounts for Earth's movement around the Sun.", "category": "random", "hook": "Not quite 24 hours!"},
    {"statement": "Fingerprints are unique to humans.", "verdict": "FALSE", "explanation": "Koalas and chimpanzees also have unique fingerprints. Koala prints are so similar to humans they could potentially confuse forensic investigators.", "category": "random", "hook": "Koala prints!"},
    {"statement": "Identical twins have identical fingerprints.", "verdict": "FALSE", "explanation": "Even identical twins have different fingerprints. Fingerprints are influenced by random factors in the womb environment, not just genetics.", "category": "random", "hook": "Unique even in twins!"},
    {"statement": "The world's first photograph was taken in 1826.", "verdict": "TRUE", "explanation": "The oldest surviving photograph is 'View from the Window at Le Gras', taken by Joseph Nicéphore Niépce around 1826–1827.", "category": "random", "hook": "First photo!"},
    {"statement": "An octopus can open a jar from the inside.", "verdict": "TRUE", "explanation": "Octopuses are highly intelligent and dexterous — they can unscrew jar lids and have been observed opening jars from both inside and outside.", "category": "random", "hook": "Clever octopus!"},
    {"statement": "The shortest war in history lasted less than an hour.", "verdict": "TRUE", "explanation": "The Anglo-Zanzibar War of 1896 lasted between 38 and 45 minutes — the shortest recorded war in history.", "category": "random", "hook": "45-minute war!"},
    {"statement": "Humans are the only animals that blush.", "verdict": "TRUE", "explanation": "Charles Darwin called blushing 'the most peculiar and most human of all expressions.' No other animal is known to blush from embarrassment.", "category": "random", "hook": "Human blush!"},
    {"statement": "Nintendo is older than most countries in Africa.", "verdict": "TRUE", "explanation": "Nintendo was founded in 1889. Most African countries gained independence after 1956. Nintendo predates virtually all of them.", "category": "random", "hook": "Ancient Nintendo!"},
    {"statement": "A jiffy is a real unit of time.", "verdict": "TRUE", "explanation": "In physics and computing, a jiffy is a real unit: in physics it's 3x10^-24 seconds; in computing it's often 1/100th of a second.", "category": "random", "hook": "In a jiffy!"},
    {"statement": "You can go blind from staring at the sun for just a few seconds.", "verdict": "TRUE", "explanation": "The sun's UV radiation can cause permanent retinal damage (solar retinopathy) in as little as a few seconds of direct gazing without eye protection.", "category": "random", "hook": "Protect your eyes!"},
    {"statement": "There is a country called 'the Former Yugoslav Republic of Macedonia'.", "verdict": "FALSE", "explanation": "That was the name temporarily used from 1993–2019. In 2019, the country officially renamed itself the Republic of North Macedonia.", "category": "random", "hook": "Name change!"},
    {"statement": "The sentence 'the quick brown fox jumps over the lazy dog' contains every letter of the alphabet.", "verdict": "TRUE", "explanation": "This is a pangram — a sentence that uses every letter of the English alphabet at least once. It's used to test typewriters and fonts.", "category": "random", "hook": "Every letter!"},
    {"statement": "Cleopatra lived closer in time to the iPhone than to the construction of the Great Pyramid.", "verdict": "TRUE", "explanation": "The Great Pyramid was built ~2560 BC. Cleopatra lived ~69–30 BC. iPhone: 2007. Cleopatra is ~2,500 years from the pyramid but ~2,000 years from today.", "category": "random", "hook": "Timeline mind-bender!"},
]

for i, item in enumerate(new_items):
    item["id"] = f"tof_{next_n + i:04d}"

result = existing + new_items
json.dump(result, open(F, "w", encoding="utf-8"), indent=2, ensure_ascii=False)
print(f"trueorfalse: {len(existing)} -> {len(result)} (+{len(new_items)})")
