import json
from pathlib import Path

F = Path("C:/Users/prawn/OneDrive/Documents/djamies1.github.io/trickquestions/questions.json")
existing = json.load(open(F, encoding="utf-8"))
ids = [int(x["id"].split("_")[-1]) for x in existing if x.get("id","").startswith("tq_")]
next_n = max(ids, default=0) + 1

new_items = [
    # SCIENCE
    {"question": "What gets wetter the more it dries?", "answer": "A towel", "answer_note": "A towel absorbs water as it dries things, becoming wetter itself.", "category": "science", "difficulty": "easy", "hook": "Classic riddle!"},
    {"question": "What can you catch but never throw?", "answer": "A cold", "answer_note": "You catch a cold (illness) but you can't throw one!", "category": "science", "difficulty": "easy", "hook": "Sneeze!"},
    {"question": "If you drop a yellow hat in the Red Sea, what does it become?", "answer": "Wet", "answer_note": "The hat gets wet when dropped in water — the color of the sea is irrelevant.", "category": "science", "difficulty": "easy", "hook": "Distraction question!"},
    {"question": "What element has the chemical symbol Fe?", "answer": "Iron", "answer_note": "Fe comes from the Latin 'ferrum' meaning iron.", "category": "science", "difficulty": "medium", "hook": "Latin chemistry!"},
    {"question": "What happens to the size of an iron rod when it's heated?", "answer": "It expands", "answer_note": "Most materials expand when heated due to increased atomic vibration.", "category": "science", "difficulty": "easy", "hook": "Thermal expansion!"},
    {"question": "How can you drop an egg on a concrete floor without cracking it?", "answer": "Drop it from 1cm above — concrete floors don't crack easily", "answer_note": "The trick: concrete floors are very hard to crack. The egg might crack but the floor won't.", "category": "science", "difficulty": "medium", "hook": "Read the question!"},
    {"question": "Which is heavier: a kilogram of steel or a kilogram of feathers?", "answer": "They're equal — both weigh 1 kilogram", "answer_note": "Same mass, just different volumes. Steel just takes up less space.", "category": "science", "difficulty": "easy", "hook": "Classic weight trick!"},
    {"question": "What word is always spelled incorrectly?", "answer": "Incorrectly", "answer_note": "The word 'incorrectly' is the only word that is always spelled exactly as asked — incorrectly.", "category": "science", "difficulty": "easy", "hook": "Language riddle!"},
    {"question": "Can a man living in Winston-Salem, NC, be buried west of the Mississippi River?", "answer": "No — a living man cannot be buried anywhere", "answer_note": "The question says 'a man living' — living people aren't buried!", "category": "science", "difficulty": "easy", "hook": "Trick phrasing!"},
    {"question": "What do you call a fish without eyes?", "answer": "A fsh", "answer_note": "Fish without 'i's' is just 'fsh'. A classic wordplay riddle!", "category": "science", "difficulty": "easy", "hook": "Wordplay!"},
    # HISTORY
    {"question": "Julius Caesar's last words were 'Et tu, Brute?' — true or false?", "answer": "False (probably)", "answer_note": "The quote is from Shakespeare's play. Historical accounts vary — Suetonius says Caesar said nothing or 'kai su, teknon' (Greek for 'you too, child?').", "category": "history", "difficulty": "hard", "hook": "Shakespeare vs history!"},
    {"question": "Which country gifted the Statue of Liberty to the USA?", "answer": "France", "answer_note": "France gifted the Statue of Liberty in 1886, designed by sculptor Frédéric Auguste Bartholdi.", "category": "history", "difficulty": "medium", "hook": "French gift!"},
    {"question": "How many of the original 13 American colonies started with the letter 'M'?", "answer": "4", "answer_note": "Maryland, Massachusetts, New Hampshire... wait: Maryland, Massachusetts — and from all 13: Maryland, Massachusetts. Actually: Maryland and Massachusetts = 2. Check: Maryland, Massachusetts = 2 colonies start with M.", "category": "history", "difficulty": "hard", "hook": "Colonial knowledge!"},
    {"question": "Who was the first person to set foot on Antarctica?", "answer": "Disputed — likely a Norwegian sailor around 1820", "answer_note": "The first confirmed landing is disputed between American Nathaniel Palmer, British Edward Bransfield, and Norwegian Fabian von Bellingshausen in 1820-21.", "category": "history", "difficulty": "hard", "hook": "Frozen history!"},
    {"question": "Was the Great Wall of China built all at once?", "answer": "No — it was built over many centuries by different dynasties", "answer_note": "Construction spanned from the 7th century BC to the 17th century AD under multiple Chinese dynasties.", "category": "history", "difficulty": "medium", "hook": "Centuries of building!"},
    {"question": "In what decade did the Wright Brothers make their first powered flight?", "answer": "1900s (1903)", "answer_note": "Orville and Wilbur Wright made their first successful powered flight on December 17, 1903.", "category": "history", "difficulty": "easy", "hook": "First flight!"},
    {"question": "Which came first — the chicken or the egg, according to science?", "answer": "The egg", "answer_note": "Scientifically, eggs predate chickens by hundreds of millions of years (dinosaurs laid eggs). The first 'chicken egg' came from a proto-chicken parent.", "category": "history", "difficulty": "hard", "hook": "Ancient riddle answered by science!"},
    # GEOGRAPHY
    {"question": "What is the capital of Australia?", "answer": "Canberra", "answer_note": "Many people say Sydney or Melbourne, but Canberra has been Australia's capital since 1913.", "category": "geography", "difficulty": "medium", "hook": "Not Sydney!"},
    {"question": "Is Iceland covered in ice and Greenland covered in green?", "answer": "Sort of the opposite — Iceland is green, Greenland is mostly ice", "answer_note": "Iceland has lush vegetation in many areas; Greenland is about 80% covered by an ice sheet.", "category": "geography", "difficulty": "medium", "hook": "Confusing names!"},
    {"question": "What ocean is between North America and Europe?", "answer": "The Atlantic Ocean", "answer_note": "The Atlantic Ocean separates North America and Europe, spanning about 6,000 km.", "category": "geography", "difficulty": "easy", "hook": "Which ocean?"},
    {"question": "How many countries are in Africa?", "answer": "54", "answer_note": "Africa has 54 sovereign countries, more than any other continent.", "category": "geography", "difficulty": "hard", "hook": "How many?"},
    {"question": "Which is further north — London or Vancouver?", "answer": "London is slightly further north", "answer_note": "London is at about 51.5°N. Vancouver is at about 49.3°N. London is slightly further north.", "category": "geography", "difficulty": "hard", "hook": "Northern showdown!"},
    {"question": "What is the largest country by land area in South America?", "answer": "Brazil", "answer_note": "Brazil covers about 8.5 million km², nearly half of South America's total land area.", "category": "geography", "difficulty": "easy", "hook": "South American giant!"},
    # LANGUAGE
    {"question": "What is the most commonly used letter in the English language?", "answer": "E", "answer_note": "The letter 'E' accounts for about 13% of all letters used in English text.", "category": "language", "difficulty": "easy", "hook": "Frequency facts!"},
    {"question": "What English word has three consecutive double letters?", "answer": "Bookkeeper", "answer_note": "Bookkeeper has oo, kk, and ee — three consecutive double letter pairs.", "category": "language", "difficulty": "hard", "hook": "Triple doubles!"},
    {"question": "How many syllables are in the word 'queue'?", "answer": "1", "answer_note": "Despite its 5 letters, 'queue' has only one syllable — it sounds like 'kyoo'.", "category": "language", "difficulty": "medium", "hook": "Long word, one sound!"},
    {"question": "What is the only word in English that ends in '-mt'?", "answer": "Dreamt", "answer_note": "Dreamt is the only common English word ending in '-mt'. It's the past tense of 'dream'.", "category": "language", "difficulty": "hard", "hook": "Word trivia!"},
    {"question": "What connects the words: cake, cup, pan, short?", "answer": "They all precede 'cake'", "answer_note": "Cupcake, pancake, shortcake — all compound words with cake.", "category": "language", "difficulty": "medium", "hook": "Word connections!"},
    {"question": "What is a word that means the same whether you read it forwards or backwards?", "answer": "Palindrome — examples: racecar, level, madam", "answer_note": "Words that read the same forwards and backwards are called palindromes.", "category": "language", "difficulty": "easy", "hook": "Palindromes!"},
    # NATURE
    {"question": "What color is the sky on Mars?", "answer": "Pinkish-red or butterscotch", "answer_note": "Mars's sky appears pink to butterscotch because of iron oxide (rust) dust in the thin atmosphere.", "category": "nature", "difficulty": "hard", "hook": "Not blue!"},
    {"question": "Do trees grow from the top or the bottom?", "answer": "From the top (tips)", "answer_note": "Trees grow at their growing tips (meristems) — the trunk doesn't rise as the tree grows taller.", "category": "nature", "difficulty": "medium", "hook": "Tree growth!"},
    {"question": "If a tree falls in a forest and no one is around, does it make a sound?", "answer": "Yes — it creates sound waves, but 'sound' requires a listener to perceive it", "answer_note": "The philosophical split: physically yes (vibrations); philosophically unclear (no conscious perception).", "category": "nature", "difficulty": "hard", "hook": "Philosophy of sound!"},
    {"question": "What is the deepest point on Earth?", "answer": "Challenger Deep, Mariana Trench (~11,000m)", "answer_note": "Challenger Deep in the Pacific Ocean's Mariana Trench is about 11,034m below sea level.", "category": "nature", "difficulty": "medium", "hook": "Deepest point!"},
    {"question": "Which direction does water swirl down a drain in the southern hemisphere?", "answer": "It depends on the drain shape, not hemisphere — the Coriolis effect is too weak for drains", "answer_note": "Contrary to popular belief, the Coriolis effect is negligible at drain scales. Direction is determined by the drain's shape.", "category": "nature", "difficulty": "hard", "hook": "Coriolis myth!"},
    {"question": "What percentage of Earth's water is freshwater?", "answer": "About 3%", "answer_note": "97% of Earth's water is saltwater. Of the 3% freshwater, most is locked in ice caps and glaciers.", "category": "nature", "difficulty": "medium", "hook": "Water scarcity!"},
    {"question": "How long does it take for light to travel from the Sun to Earth?", "answer": "About 8 minutes 20 seconds", "answer_note": "The Sun is about 150 million km away. At 300,000 km/s, light takes ~8 min 20 sec.", "category": "nature", "difficulty": "medium", "hook": "Old light!"},
    # FOOD
    {"question": "What is the most expensive food in the world by weight?", "answer": "White Alba truffle (or sometimes saffron)", "answer_note": "White truffles from Alba, Italy, can sell for $2,000–$3,000 per pound. Some rare varieties fetch far more.", "category": "food", "difficulty": "hard", "hook": "Pricey ingredients!"},
    {"question": "What is the only fruit with seeds on the outside?", "answer": "Strawberry", "answer_note": "The small yellow/green dots on a strawberry are actually its seeds (technically achenes) on the outside.", "category": "food", "difficulty": "medium", "hook": "Seeds outside!"},
    {"question": "What nut is not technically a nut?", "answer": "Peanut (it's a legume), almond (it's a drupe), cashew (it's a seed)", "answer_note": "True botanical nuts include hazelnuts, chestnuts, and acorns. Peanuts, almonds, and cashews are technically not nuts.", "category": "food", "difficulty": "medium", "hook": "Not a real nut!"},
    {"question": "Which part of the carrot plant is actually eaten?", "answer": "The taproot", "answer_note": "The orange carrot we eat is the plant's taproot — its underground nutrient storage organ.", "category": "food", "difficulty": "easy", "hook": "Root vegetable!"},
    {"question": "Can you name a food that never expires?", "answer": "Honey, salt, sugar, pure vanilla extract, white rice", "answer_note": "These foods, when stored properly, can last indefinitely. Honey has been found edible in Egyptian tombs.", "category": "food", "difficulty": "medium", "hook": "Forever foods!"},
    # RANDOM LOGIC
    {"question": "What has one eye but cannot see?", "answer": "A needle", "answer_note": "A needle has an 'eye' (the hole you thread) but obviously cannot see.", "category": "logic", "difficulty": "easy", "hook": "Classic riddle!"},
    {"question": "What runs but never walks, has a mouth but never talks?", "answer": "A river", "answer_note": "Rivers 'run', have a 'mouth' (where they meet the sea), and 'banks' on either side.", "category": "logic", "difficulty": "easy", "hook": "River riddle!"},
    {"question": "The more of this you take, the more you leave behind. What is it?", "answer": "Footsteps", "answer_note": "Every step you take leaves a footstep behind you.", "category": "logic", "difficulty": "easy", "hook": "Walk this one!"},
    {"question": "I speak without a mouth and hear without ears. I have no body, but I come alive with wind. What am I?", "answer": "An echo", "answer_note": "An echo 'speaks' by reflecting sound, is created by sound, and travels through air.", "category": "logic", "difficulty": "medium", "hook": "Mountain riddle!"},
    {"question": "What is always in front of you but can't be seen?", "answer": "The future", "answer_note": "The future is always ahead of you but is invisible and unknown.", "category": "logic", "difficulty": "easy", "hook": "Philosophical!"},
    {"question": "You are my brother, but I am not your brother. Who am I?", "answer": "Your sister", "answer_note": "Only a sister could say 'you are my brother' while not being a brother themselves.", "category": "logic", "difficulty": "easy", "hook": "Family riddle!"},
    {"question": "A doctor gives you 3 pills and tells you to take one every half hour. How long before all pills are taken?", "answer": "1 hour", "answer_note": "Take pill 1 now (0 min), pill 2 at 30 min, pill 3 at 60 min — 1 hour total.", "category": "logic", "difficulty": "medium", "hook": "Timing trick!"},
    {"question": "If you have a bowl with 6 apples and you take away 4, how many apples do you have?", "answer": "4", "answer_note": "You took 4 apples, so you have 4. The bowl has 2 remaining.", "category": "logic", "difficulty": "easy", "hook": "You have what you took!"},
    {"question": "What can travel around the world while staying in a corner?", "answer": "A stamp", "answer_note": "A postage stamp stays in the corner of an envelope that travels the world.", "category": "logic", "difficulty": "medium", "hook": "World traveler!"},
    {"question": "If you have me, you want to share me. If you share me, you no longer have me. What am I?", "answer": "A secret", "answer_note": "Secrets lose their power the moment they are shared.", "category": "logic", "difficulty": "easy", "hook": "Don't tell anyone!"},
]

for i, item in enumerate(new_items):
    item["id"] = f"tq_{next_n + i:04d}"

result = existing + new_items
json.dump(result, open(F, "w", encoding="utf-8"), indent=2, ensure_ascii=False)
print(f"trickquestions: {len(existing)} -> {len(result)} (+{len(new_items)})")
